### ISSUE TITLE
[Bug]: Public endpoint /v1/images started to answer with 500

### ISSUE THREAD

**Issue by pasaranax** [civitai/civitai#1005]
### What happened?

On Feb 2nd approximately after 20:00 UTC I noticed that /api/v1/images became answering with status code 500 on almost any requests with parameters. Almost because some requests are processing normally, but it seems cached ones because they are ones I already sent when api was answering normally. Requests without parameters work well.

### Steps to reproduce the problem

1. Go to https://civitai.com/api/v1/images - it is ok
2. Go to https://civitai.com/api/v1/images?limit=100 - it returns "Internal Server Error"

### What should have happened?

Requests with parameters like https://civitai.com/api/v1/images?limit=10 should return json with results

### What platforms do you use to access the site?

Windows, Linux

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

Filtering on the website works as expected. Google Chrome shows requests with parameters work well. The example that I sniffed with the browser.
```
https://civitai.com/api/trpc/image.getInfinite?input=%7B%22json%22%3A%7B%22period%22%3A%22Week%22%2C%22sort%22%3A%22Most%20Reactions%22%2C%22view%22%3A%22feed%22%2C%22types%22%3A%5B%22image%22%2C%22video%22%5D%2C%22cursor%22%3Anull%2C%22authed%22%3Atrue%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22cursor%22%3A%5B%22undefined%22%5D%7D%7D%7D
```
It seems the problem is only with public API. Any combination of parameters causes the server error. Syntactically incorrect parameters cause validation error. Example: https://civitai.com/api/v1/images?limit=abc
Not existing parameters causes server error. Example: https://civitai.com/api/v1/images?limitttttt=100
I reproduced the problem in the browser and from Python code.
Other endpoints seem work, but I tried only couple of them.

**Comment by SinaYa** [comment]
I don't think they have plans to fix it. there are so many open bugs.

**Comment by pasaranax** [comment]
> I don't think they have plans to fix it. there are so many open bugs.

Hope they are silent because of the weekend

**Comment by kfzzzzzz** [comment]
现在这个接口还是未修复吗？

**Comment by viralesveras** [comment]
> 现在这个接口还是未修复吗？
Translated: Is this interface still broken?

As of now, yes this is still broken. Hopefully they'll fix it soon.
就目前而言，是的，这仍然是坏的。 希望他们能尽快修复它。

**Comment by kfzzzzzz** [comment]
您好，您的邮件已经收到，相关事宜将尽快处理。（请勿回复此邮件）

**Comment by f4cyw** [comment]
is it working? 
[ https://civitai.com/api/v1/images  with parameters ] is not working still.....
Do you guys have any ideas to gathering images data?

**Comment by hw25io** [comment]
> is it working?

Doesn't look like, no ... Does anyone from the team even read these bug reports or is the project here more or less dead?

**Comment by MajMorse** [comment]
Please retest

**Comment by hw25io** [comment]
> Please retest

At least from my point of view, everything is working fine again. Thank you very much for fixing it!

**Comment by fpv999** [comment]
it works!
