### ISSUE TITLE
[Bug]: api nsfw=false The request time will increase to over 20 seconds.

### ISSUE THREAD

**Issue by WuKaiYi** [civitai/civitai#1007]
### What happened?

https://civitai.com/api/v1/models?limit=15&page=1&types=LORA&baseModels=SD 1.5&nsfw=false

It took 30 seconds to obtain the information.

https://civitai.com/api/v1/models?limit=15&page=1&types=LORA&baseModels=SD 1.5

Remove nsfw=false only takes 3 seconds.

### Steps to reproduce the problem

https://civitai.com/api/v1/models?limit=15&page=1&types=LORA&baseModels=SD 1.5&nsfw=false

### What should have happened?

The time it should take is within 10 seconds.

**Comment by gianpaj** [comment]
it took 4.03 sec in avg (3.26 + 5.69+3.15)

<img width="1408" alt="image" src="https://github.com/civitai/civitai/assets/899175/fda023d4-4ac9-4eec-a263-884eae3185a0">

<https://civitai.com/api/v1/models?limit=15&page=1&types=LORA&baseModels=SD%201.5&nsfw=false>
