### ISSUE TITLE
[Bug]: Rest Api Get Models sort param is broken

### ISSUE THREAD

**Issue by warycat** [civitai/civitai#1047]
### What happened?

The GET request below is not returning correct objects.
https://civitai.com/api/v1/models?page=1&limit=10&query=&types=Checkpoint&sort=Most+Downloaded&period=AllTime&baseModels=SD+1.5&nsfw=true

### Steps to reproduce the problem

1. Go to https://civitai.com/api/v1/models?page=1&limit=10&query=&types=Checkpoint&sort=Most+Downloaded&period=AllTime&baseModels=SD+1.5&nsfw=true

### What should have happened?

Realistic Vision should be the first item in the response

**Comment by warycat** [comment]
It only returns the newest items.

**Comment by rikkooo** [comment]
The same. No way to sort models properly :, /

**Comment by ScreNN** [comment]
Yes, it's a serious problem
