### ISSUE TITLE
[Bug]: API `models` endpoint problems.

### ISSUE THREAD

**Issue by BlafKing** [civitai/civitai#1078]
### What happened?

There are currently quite a few problems with the models endpoint, these are the one's I could find:

1. The `sort` parameter sometimes returns results that are not right, for example, when searching: https://civitai.com/api/v1/models?limit=15&sort=Newest&period=AllTime&query=dream
It shows 15 models (as requested) but none have any `modelVersions` it seems they are all already deleted from CivitAI.
Additionally it does not contain a `nextPage` URL, it seems that this happens whenever all the returned models have empty `modelVersions` as it does supply a nextPage when the same request is used with a higher `limit` as it then contains some models with non empty `modelVersions`:
https://civitai.com/api/v1/models?limit=40&sort=Newest&period=AllTime&query=dream

2. The `nextPage` is broken very often resulting in an internal server error, example URL:
https://civitai.com/api/v1/models?limit=15&period=AllTime&query=dream&sort=Most%20Downloaded&cursor=12976%3A2764%3A4481

3. The `types` parameter does not seem to influence search results if a `query` parameter is used in the same request, example URL:
https://civitai.com/api/v1/models?limit=15&query=dream&types=LORA
https://civitai.com/api/v1/models?limit=15&query=dream

### Steps to reproduce the problem

Attempt to use any of the API Request URLs provided as examples.

### What should have happened?

API should function as expected.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Brave

**Comment by zixaphir** [comment]
Same issues here.
