### ISSUE TITLE
[Bug]: `nsfw` parameter/return broken on Public API

### ISSUE THREAD

**Issue by BlafKing** [civitai/civitai#1099]
### What happened?

Currently the `nsfw` parameter has no effect on search results when using the `models` endpoint on the Public API, they remain the same when setting it as `false` or `true`

Additionally the returned `nsfw` field on each model in a request to the `models` endpoint isn't always correct, here is an example query/URL where all the results should be NSFW, since this is what they were before the new NSFW system.
https://civitai.com/api/v1/models?query=cowgirl&limit=30&sort=Most%20Downloaded

Most of the resulting models contain `"nsfw": true` as expected, but some return `"nsfw": false` while they are clearly NSFW models.

### Steps to reproduce the problem

1. Attempt to use the `nsfw` parameter in a request to the Public API's `models` endpoint
2. Use the example URL provided. results in incorrect `nsfw` returns

### What should have happened?

1. The `nsfw` parameter should have impact on search results
2. All `nsfw` fields returned for each model should be correct, to allow proper filtering.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Brave

**Comment by minhnhat0709** [comment]
I have the same problem too

**Comment by BlafKing** [comment]
seems to be fixed 👍🏻 

behaviour now is that it does not return nsfw by default and only shows NSFW models when setting the parameter to true
