### ISSUE TITLE
[Bug]: image API is not returning images at requested nsfw level

### ISSUE THREAD

**Issue by gourmetdigests** [civitai/civitai#1101]
### What happened?

Querying the image endpoint URL https://civitai.com/api/v1/images, not all the expected images are returned for any given nsfw level.

### Steps to reproduce the problem

Example **15** images available in total  - 4 at PG, 11 at PG-13 - for this post:
https://civitai.com/posts/1350490

Using no nsfw param - only 4 items returned (the PG ones) but should be all 15:
https://civitai.com/api/v1/images?postId=1350490

Using "None" nsfw param, only 4 items returned (the PG ones):
https://civitai.com/api/v1/images?postId=1350490&nsfw=None

Using "Soft" nsfw param, 11 items returned (only the PG-13), but should also include the 4 PG ones too:
https://civitai.com/api/v1/images?postId=1350490&nsfw=Soft

Using "X" nsfw param, 0 items returned but should be all 15 images:
https://civitai.com/api/v1/images?postId=1350490&nsfw=X

### What should have happened?

1. Not specifying any nsfw level should return ALL images, regardless of their nsfw rating
2. Specifying a nsfw level should return all images up-to-and-including that rating.

### What platforms do you use to access the site?

MacOS

### What browsers do you use to access the site?

Apple Safari

**Comment by manuelurenah** [comment]
We have already fixed this issue @gourmetdigests I'll be closing the issue, but feel free to open it if you're still experiencing the problem. Thanks for pointing it out!
