### ISSUE TITLE
[Bug]: No modelVersions.createdAt reponse field

### ISSUE THREAD

**Issue by hellomynameisleo** [civitai/civitai#1128]
### What happened?

The https://civitai.com/api/v1/models api no longer returns the modelVersions.createdAt response field anymore

### Steps to reproduce the problem

1. Send request to https://civitai.com/api/v1/models
2. Get modelVersions.createdAt reponse field

### What should have happened?

The modelVersions.createdAt reponse field should be included in the return data from the https://civitai.com/api/v1/models api

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by manuelurenah** [comment]
Hey @hellomynameisleo we have deprecated that field in favor for `publishedAt`, you should use that one instead
