### ISSUE TITLE
[Bug]: API pagination is broken

### ISSUE THREAD

**Issue by worthlesscog** [civitai/civitai#1150]
### What happened?

Following metadata nextPage links is enough for model API calls to fail

### Steps to reproduce the problem

go to https://civitai.com/api/v1/models
follow metadata/nextPage links until you get to
https://civitai.com/api/v1/models?cursor=76%3A341%3A146864&limit=100&nsfw=true

the next link fails -
{"message":"An unexpected error occurred","error":"URI malformed"}

### What should have happened?

nextPage should not fail

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by manuelurenah** [comment]
Thanks for bringing this into our attention @worthlesscog we have addressed the issue and it should be patched very shortly. If this is still an issue for you, please feel free to open the discussion again
