### ISSUE TITLE
[Bug]: Get Model information by API is miss creator fields

### ISSUE THREAD

**Issue by ChiaYen-Kan** [civitai/civitai#1153]
### What happened?

when get model information by API is miss creator fields

### Steps to reproduce the problem

download this model information by API
https://civitai.com/api/v1/models/112403

### What should have happened?

should be have creator fields in response json

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by manuelurenah** [comment]
Hey @ChiaYen-Kan there are some models without a creator that we host in our site. This means that they were imported from another site or the original creator decided to delete their account, but keep their models on our site by transferring their ownership to us. Hope this helps!
