### ISSUE TITLE
[Bug]: "Hidden" Filter not working as Intended

### ISSUE THREAD

**Issue by Basilicum** [civitai/civitai#1200]
### What happened?

![image](https://github.com/civitai/civitai/assets/1304955/839926c0-16cb-454d-898d-20e555fc8d07)

I can only assume the "Hidden" Feature is a way to Blacklist Tags. Sadly, since Time Period and Checkpoint Type are so Broad and cannot be turned off, it hides... everything.

If it isn't a Blacklist Feature then excuse this Bug Report. I will then write e Feature Request for a Blacklist of Tags. 

### Steps to reproduce the problem

1. Go to Filters
2. Press Hidden
3. Nothing will show up anymore

### What should have happened?

Filtering Seen things by Tags

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome

**Comment by manuelurenah** [comment]
Hey @Basilicum , the hidden filter in this case works for showing the models you have hidden individually.

In case you didn't know, that's possible by opening the context menu in a model card and selecting the option from there
![image](https://github.com/user-attachments/assets/7e6230ce-c913-419d-a8c7-9c6e1128769e)

Hope this helps!
