### ISSUE TITLE
[Bug]: Missing response metadata

### ISSUE THREAD

**Issue by vujadin** [civitai/civitai#1205]
### What happened?

When making request to fetch models (https://civitai.com/api/v1/models) response metadata doesn't contain some fields (that were there before). Missing fields are: totalPages, prevPage, totalItems. It was working ok until recently.

![image](https://github.com/civitai/civitai/assets/4639385/3e9fd165-780d-460b-8e29-85eb1101b00a)

### Steps to reproduce the problem

Execute:
curl https://civitai.com/api/v1/models?limit=3 -H "Content-Type: application/json" -X GET

you will get:
![image](https://github.com/civitai/civitai/assets/4639385/bc9a7776-755b-43fe-b36e-f53757953341)

### What should have happened?

Response should contain totalPages, prevPage, totalItems fields in metadata.

**Comment by manuelurenah** [comment]
Hey @vujadin this has been deprecated and you should use cursor pagination instead to query more items from the public API. You can use the `nextPage` field from `metadata` to get the next items. Hope this helps!
