### ISSUE TITLE
[Bug]: API Response Cursors Looping Back on Themselves

### ISSUE THREAD

**Issue by tk101-fs** [civitai/civitai#1241]
### What happened?

Seeing weird behavior on API with cursors / pages looping back to themselves. With this endpoint example below, you can follow about 7 cursors before looping back on itself:

https://civitai.com/api/v1/images?modelId=20282_Henmix_Real&modelVersionId=70458_v4.0&sort=Most%20Reactions&nsfw=None&limit=200

This endpoint response ends with Cursor 7|5|2|4453803, which then leads down the following sequence of cursors over the next 6 pages:
5|3|2|1306097
4|2|2|6061916
3|2|1|4452440
2|2|0|9218155
1|1|0|2320754
0|0|0|1942537
_7|5|2|4453803 (**SAME AS INITIAL CURSOR!**)_

Now when following that cursor (0|0|0|1942537), it leads you BACK to cursor 7|5|2|4453803 and you end up in an endless loop of following this sequence of cursors through the same 7 pages. This is unexpected and appears to be a bug -- The expected behavior would be that once there are no more images, the "nextCursor" item in the metadata block would be empty and the endpoint response would not lead to any further cursors/pages.

### Steps to reproduce the problem

Starting from endpoint URL https://civitai.com/api/v1/images?modelId=20282_Henmix_Real&modelVersionId=70458_v4.0&sort=Most%20Reactions&nsfw=None&limit=200 , follow the cursors and you will end up in an endless loop.

### What should have happened?

When no more pages are available, nextCursor should not point anywhere so there is a clean end.
If this problem is specific to the Most Reactions sort, it could be because once it hits the block of images with zero reactions, it doesn't know how to order them for subsequent query responses? It would make sense to return results newest to oldest from that point forward.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome, Microsoft Edge

**Comment by manuelurenah** [comment]
hey guys, thank you for bringing this to our attention. I've pushed a fixed for this here https://github.com/civitai/civitai/commit/f4557d2ef430663362433acbd684acecfa841f78 and should be out in our next release
