### ISSUE TITLE
[Bug]:  Unable to add a Lora - hidden 

### ISSUE THREAD

**Issue by evilbob44** [civitai/civitai#1263]
### What happened?

After I click +Add, and enter my search information, the Lora does not appear. Scrolled to the bottom of what Lora'a appeared,  scrolled to the top of the displayed Lora's and this message appears: " 1models have been hidden due to your settings."  I have toggled off then on Show Mature Content in Account Settings.  I have logged out and then back into the site. The model shows in the Vault; however, it is not refreshed.

### Steps to reproduce the problem

1. Click Create
2. Clicked Swap
3. Selected the model as described in the models Recommended Resources:  Realistic Vision V6.0 B1
4. Clicked the +Add button
5. Entered my search criteria in the Search box
6. My searched Lora does NOT display; however, some Lora's display
7. Scrolled all the way down through the Lora's that displayed
8. Scrolled up all the way to the top of the displayed Lora's
9. The searched Lora does NOT display
10. Saw this message: "1 models have been hidden due to your settings."

![model hidden](https://github.com/civitai/civitai/assets/174799062/1e737d35-61dd-4a4c-b467-a3fbc981de50)

### What should have happened?

I assume that the Lora would display after clicking the +Add button and entering my search criteria.  

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

New to github, I hope this information is enough to help.

**Comment by manuelurenah** [comment]
Hey, if this is the model in question https://civitai.com/models/409804, seems like you're trying to use a model that depicts a real person. Per our ToS, we don't allow on-site generation with resources that have the likeness of a real person. You're free to download it and generate using a third party service. Sorry for the inconveniences
