### ISSUE TITLE
[Bug]: stripping username underscore characters - malforming user profile paths

### ISSUE THREAD

**Issue by DreamOfGit** [civitai/civitai#127]
### What happened?

If you click a user in the 'Uploader' field on a model page that has a underscore in their name, it will strip the underscore in the redirected path 

### Steps to reproduce the problem

1) Click user in the 'Uploader' field on a model page that has a underscore in their name (eg, cool_person)
2) cool_person will resolve to https://civitai.com/user/coolperson which shows a "No Results Found" page.

--

If you explicitly search the user in the search bar (@cool_person) it will work correctly.

### What should have happened?

Dunno, are you intentionally stripping underscores for some reason?

**Comment by JustMaier** [comment]
Thanks for the heads up. We just revamped the username system to deal with invalid characters and had left a slugify function in that was no longer needed.

We've fixed that and the change is being deployed now (should be live in about 10 minutes)

Feel free to re-open if you still notice any issues with it still 👍
