### ISSUE TITLE
[Bug]: Getting 429 when requesting 200 images from page=2

### ISSUE THREAD

**Issue by sarfatyAtTau** [civitai/civitai#1286]
### What happened?

Using the REST api (in python), I tried to fetch 200 images from page 2. Repeatedly received error 429. I believe I found the bug location, but I am not an experienced user of type script.

### Steps to reproduce the problem

`params = {
    "limit": 200, 
    'nsfw': 'false',
    'sort': 'Most Reactions',
    'period': 'AllTime',
    'page': 2,
}`
`response = requests.get("https://civitai.com/api/v1/images", params=params)`
`print(response.status_code)`

### What should have happened?

Should got a status code of 200.

### What platforms do you use to access the site?

Linux

### Additional information, context and logs

On one hand, in file /civitai/src/server/utils/pagination-helpers.ts, line 9:
`export function getPagination(limit: number, page: number | undefined) {
  const take = limit > 0 ? limit : undefined;
  const skip = page && take ? (page - 1) * take : undefined;
  return { take, skip };
}`
The above function calculates the "skip" in units of [images]. it can be seen in the calculation `(page-1)*take`.

On the other hand, in file /civitai/src/pages/api/v1/images/index.ts, line 80:
` ({ skip } = getPagination(limit, page));
      if (skip && skip * limit > 10000)
        // Enforce new paging limit
        return res
          .status(429)
          .json({ error: "You've requested too many pages, please use cursors instead" });`
The max limit is calculated as if `skip` represents page number, while it actually holds number of images. Can see that in the calculation `skip * limit > 10000`.

The result is that even for page=2 and limit=200, we get:
skip = 200
skip * limit = 200 * 200 = **40,000**

**Comment by manuelurenah** [comment]
Thanks for bringing this into our attention @sarfatyAtTau we've updated the endpoints here https://github.com/civitai/civitai/commit/e4808e1bbdca82dc93925143a8920319a76f3b44 to mitigate the issue and we'll be out shortly. We do recommend, if you're going to be querying a big batch of images, to use cursor pagination instead. We conveniently return the `nextPage` inside the `metadata` field when getting a response from the API and you should be using that to keep getting more results.

Hope this helps!
