### ISSUE TITLE
[Bug]: REST API not returning images.meta for models or model-versions

### ISSUE THREAD

**Issue by jcsmirnio** [civitai/civitai#1297]
### What happened?

REST API queries for models (by id or unfiltered) or model-versions (by id or by hash) do not return an `images.meta` key/field.

### Steps to reproduce the problem

1. Load e.g. https://civitai.com/api/v1/model-versions/646523 or https://civitai.com/api/v1/models/277058

### What should have happened?

According to the REST API reference (https://github.com/civitai/civitai/wiki/REST-API-Reference) the models and model-versions endpoints should return either an object containing image generation data or null for each of a model version's sample images in `images.meta`. This was working as recently as 7/24 but at least as of 7/29 `images.meta` is not present.

### Additional information, context and logs

It doesn't look like there have been recent changes to  [`/src/pages/api/v1/model-versions/[id].ts
`](https://github.com/civitai/civitai/blob/main/src/pages/api/v1/models/%5Bid%5D.ts), [`/src/pages/api/v1/models/[id].ts
`](https://github.com/civitai/civitai/blob/main/src/pages/api/v1/model-versions/%5Bid%5D.ts), [`/src/pages/api/v1/model-versions/by-hash/[hash].ts
`](https://github.com/civitai/civitai/blob/main/src/pages/api/v1/model-versions/by-hash/%5Bhash%5D.ts), but I did see this commit which mentions "removing 'meta' from image query" (thought it seems to still be returned by the images API...), so I'm not sure if this is an intended change to the API or just something broken by changes elsewhere.

**Comment by bkdiehl** [comment]
Thanks for reporting this. Looks like I missed updating those endpoints for backwards compatability. The fix for this is ready, and it should be published soon.
