### ISSUE TITLE
[Bug]: Incredibly slow downloads

### ISSUE THREAD

**Issue by eadnams22** [civitai/civitai#138]
### What happened?

Downloads have been incredibly slow since yesterday, despite a stable gigabit connection. Taking 12 hours+ with some models (depending on the size).

Is there some kind of 24 hour bandwidth cap? If so, I couldn’t find it documented anywhere.

### Steps to reproduce the problem

1. Go to any model
2. Press download
3. Observe download speeds

### What should have happened?

A quick and easy download at high speeds.

### What platforms do you use to access the site?

Windows, Linux, MacOS

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

If this is working as intended, thats fine, just wasn’t documented or notified anywhere I could see. :)

**Comment by eadnams22** [comment]
Now they're back at full speed again. Interesting!

**Comment by eadnams22** [comment]
Aaaah! That’d do it! Thanks!

**Comment by egoegoegoegoego** [comment]
> I've been seeing a few people mention this recently so in case anyone else experiences this issue it'll be good to have this as a record:
> 
> Downloads are done directly between you and your nearest Cloudflare region node. If you experience a slow download, it's likely that you are one of the first in your region to request that file. When that happens, Cloudflare needs to pull the data from another region's node which can be really slow. However, once the data has been pulled to the node in your region it should be fast for you and anyone else in your region. So, if you're experiencing a slow download, at least you can feel good knowing that you're making it so that someone else in your region can download it faster 😛

dang bro it seems like I'm the sacrificial lamb as all my downloads are under 100kbps but the same files if found on huggingface are giving around 2-3 mbps

**Comment by JustMaier** [comment]
@egoegoegoegoego Is this your house? 🤣 
![image](https://github.com/civitai/civitai/assets/607609/1702c0b1-b30a-4450-816c-e4dce20241b3)

Is it just recently that it started being slow for you? Or has it always been like that?
