### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sovos15** [civitai/civitai#1385]
### What happened?

Second time now the stie stopped tracking my buzz and just lets me generate unlimited free images.

### Steps to reproduce the problem

run low on buzz.
generate images.
get lucky.

### What should have happened?

I should not be able to keep generating images buzz free.
my buzz should go down when i generate images
you should just check the server balance and not create such an insanely obvious way to just set the local variable to rob you of server time.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

[Head](https://pastebin.com/XHB61UEC)
[Body](https://pastebin.com/pad1QdWd)

**Comment by sovos15** [comment]
Maybe have an internal 2FA paired between balance and generation to limit damage in worst cases while structuring things so that the balance is routinely tracked before generation and logically standing the balance between any call for generation and the generation system itself.

**Comment by manuelurenah** [comment]
@sovos15 I'm having trouble trying to reproduce this, can you please share more information about it? We do check if you have buzz balance in the backend, that's why it's surprising to me that you were able to generate images even when you have run out of buzz. Can you please share your civitai username?

**Comment by sovos15** [comment]
I'm sovos on civitai you can see this art set should have your metadata on
it.
https://civitai.com/models/777126/canabis-dataset
all done for free, figured it would make a good celebration of
civitai.green and it has been well received.
I have seen this error a third time now. A common factor seems to be having
multiple tabs of civitai up. Like checking what you've posted most recently
in one tab and what's most popular of your work in a second (i usually work
with chatgpt and need to grab images from there to show it for context)
before working in a third civitai window to generate content. If you can't
just keep running when you run out of buzz then like some stuff in a fourth
tab. Then go back and generate more stuff, and like more stuff. More
chances for the error to happen in a given day and I don't see it every
day. I'm not doing that intentionally mind you it just happens to be how
I'm using the platform right now and due to flux I imagine many others are
as well. If you want to come up with a "help" code I can use as a prompt to
get your attention I could use that as the prompt next time the error
happens and maybe you can search that exact instance out more easily.

If there's anything else i can do to help you, feel free to reach out.

**Comment by sovos15** [comment]
Just happened a fourth time, fixes the glitch if you get some more buzz
while you have it going.

**Comment by sovos15** [comment]
Got it again, doing a set of "it's wednesday my dudes" to schedule out as
many future sundays as possible. Hopefully that creates a nice big stain on
the record for you to look at.

**Comment by manuelurenah** [comment]
@sovos15 Thanks for reporting back! This is all really useful and we are looking into potential fixes for it, will let you know when the fix is out

**Comment by sovos15** [comment]
https://github.com/user-attachments/assets/36b1cd6b-d82b-4a61-85fa-75040410ef27

**Comment by manuelurenah** [comment]
Hey @sovos15 we have released a fix for this recently, hopefully you won't experience this behavior anymore. Let us know if this is still an issue for you. Hope this helps!

**Comment by sovos15** [comment]
![image](https://github.com/user-attachments/assets/ff386da3-5bd2-4502-9585-0b5aa1c805d6)
Confirmed, fixed.

**Comment by sovos15** [comment]
Closed
