### ISSUE TITLE
[Bug]: home forgets defaults

### ISSUE THREAD

**Issue by sovos15** [civitai/civitai#1414]
### What happened?

https://github.com/user-attachments/assets/d3065803-cfa2-4a8a-aec4-aaaf7b714bff

### Steps to reproduce the problem

1. check a bunch of notifications 
2. refresh some of them (the work around for it not taking you right to a comment, bug report for that to come)
3. click the civitai banner to go home

### What should have happened?

You should go to your customized home not the default home. 

### Additional information, context and logs

Bug reports will continue until morale improves.

**Comment by sovos15** [comment]
Really pervasive issue. Just aggressively shoving that curated content down my throat. Shouldn't have "a" curator. You have a website full of people from all walks of life and choose to set up a god head like this it sickens me every time I look at it. 
![Screenshot 2024-10-15 182640](https://github.com/user-attachments/assets/40f43e7d-8a61-4c66-bf44-b44ce15d3f38)

**Comment by sovos15** [comment]
https://github.com/user-attachments/assets/8ad0f7a5-6c55-4f90-a6f9-9c698fe8a690

**Comment by sovos15** [comment]
Seems it's the refresh that does it.
https://github.com/user-attachments/assets/6d0aa53d-ec0a-4334-bb87-11c96aa25dd4

**Comment by sovos15** [comment]
Just vile that you do this at all let alone shove it in my face every five seconds. You're publishing there. People pay you and you cherry pick them. Vile shit. Scummy. Sleep poorly. 
https://github.com/user-attachments/assets/46ba68e3-5c44-4973-8aaa-2236da27603f

**Comment by manuelurenah** [comment]
@sovos15 There's a fix queued up for next release that will hopefully resolve the issue. We have tracked it down and it seems to be cloudflare cache related.
