### ISSUE TITLE
[Bug]: Drop in fails

### ISSUE THREAD

**Issue by sovos15** [civitai/civitai#1416]
### What happened?

https://github.com/user-attachments/assets/09bf7e57-49d7-49cf-876d-5cf7c1ec6840

### Steps to reproduce the problem

1. Go to comments and drag an image over the comment box (top and bottom)
2. note that there are lines that appear to indicate where to drop the image to insert it
3. hold the image over one of those lines and drop it
4. note that the image does not insert, and in fact opens a new tab

### What should have happened?

The image should be inserted and a new tab should not open

### Additional information, context and logs

Bug reports will continue until morale improves.

**Comment by manuelurenah** [comment]
Hey @sovos15 thank you for keeping an eye on all these bugs and making the reports. Unfortunately, we don't support dropping images in comment box and we are not planning to support it for now. Hope that helps!

**Comment by sovos15** [comment]
Then remove the lines that indicate it's implemented.
