### ISSUE TITLE
[Bug]: Workflow Leak

### ISSUE THREAD

**Issue by sovos15** [civitai/civitai#1417]
### What happened?

Your workflow leaked.
![image](https://github.com/user-attachments/assets/860abe8c-2362-4b4e-a7c2-965b40e1da22)
![image](https://github.com/user-attachments/assets/ea012054-1fb8-4f5f-b128-dc9eece1081c)

### Steps to reproduce the problem

1. Go to generator and make something
2. Drag the preview to the tab bar to make a new tab with it
3. save the image from the new tab
3. drop the saved image into ComfyUI
4. use the same models, get the same result.

### What should have happened?

You should have gotten a message from ComfyUI saying "Unable to find workflow in _____"
or
You should toss in an easter egg or something to detract from how plain it is.

### Additional information, context and logs

Bug reports will continue until morale improves.

**Comment by sovos15** [comment]
Flux to SD1.5 
https://github.com/user-attachments/assets/f218b265-4157-48ad-9e32-2ca35ef8f5b4

**Comment by Geeknasty** [comment]
What you are experiencing is not a "workflow leak."

This is a feature of ComfyUI. ComfyUI will read metadata stored in the "A1111 format" and will then create a standard workflow using the detected parameters.

Here is the metadata of the image you shared.
```
ExifTool Version Number         : 12.84
File Name                       : 375994167-860abe8c-2362-4b4e-a7c2-965b40e1da22.jpg
Directory                       : D:/SD-Tools/Exiftool
File Size                       : 210 kB
Zone Identifier                 : Exists
File Modification Date/Time     : 2024:10:18 10:15:38-04:00
File Access Date/Time           : 2024:10:18 10:18:00-04:00
File Creation Date/Time         : 2024:10:18 10:17:53-04:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Exif Byte Order                 : Little-endian (Intel, II)
User Comment                    : (8-bit pixel art character:1.5), (female javazon warrior:1.4), holding javelin and shield, (golden ring on spear hand:1.2), (ornate necklace:1.2), (decorative helmet:1.3), (sturdy breastplate:1.3), (battle kilt:1.2), (leather sandals:1.2), (gothic fantasy equipment:1.3), (limited color palette:1.2), (simple shading), (pixelated textures:1.3), standing idle pose, (action-ready stance:1.1), (light glow on magical equipment:1.2), (dark fantasy theme), (isometric display), (blurry:-1.3), (photorealism:-1.5), (soft edges:-1.2), (bright modern colors:-1.3), (detailed rendering:-1.4).Negative prompt: .Steps: 4, Sampler: Undefined, CFG scale: 1, Seed: 249112025, Size: 832x1216, Clip skip: 2, Created Date: 2024-10-12T23:44:54.8485507Z, Civitai resources: [{"type":"checkpoint","modelVersionId":699279,"modelName":"FLUX","modelVersionName":"Schnell"}], Civitai metadata: {"remixOfId":33730115}
Image Width                     : 832
Image Height                    : 1216
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 832x1216
Megapixels                      : 1.0
```

As you can see, the workflow is not contained in the metadata.

Instead, the generation parameters are read by ComfyUI and a graph is built: https://github.com/Comfy-Org/ComfyUI_frontend/blob/main/src/scripts/pnginfo.ts#L157

**Comment by sovos15** [comment]
I did not know that, thank you. Closing.
