### ISSUE TITLE
[Bug]: Hidden Reactions

### ISSUE THREAD

**Issue by sovos15** [civitai/civitai#1419]
### What happened?

https://github.com/user-attachments/assets/f70188d8-3df6-4944-9382-4351cb40451b

### Steps to reproduce the problem

1. Post something
2. Hit a milestone
3. Get a notification about it
4. Check out what hit a milestone
5. See that there are missing reactions

### What should have happened?

You should have seen five or more reactions on the image.

### Additional information, context and logs

Bug reports will continue until moral improves

**Comment by archecave861** [comment]
Same problem
![1](https://github.com/user-attachments/assets/8cb76a7a-be63-474c-b596-17006da412e1)
![2](https://github.com/user-attachments/assets/c6739c1a-0020-497f-885e-71701dcff0e5)

**Comment by archecave861** [comment]
Same problem
![1](https://github.com/user-attachments/assets/43e14dbb-ec6e-456d-959e-e0dfccdf87e4)
![2](https://github.com/user-attachments/assets/4da199bc-0887-4794-be8b-c6fdc22603fb)

**Comment by sovos15** [comment]
Yeah it's still an issue.
https://github.com/user-attachments/assets/79259e4c-07b9-4970-a50e-81ebda40e9ca

**Comment by archecave861** [comment]
Reactions have appeared! Everything is now normal for you too.

**Comment by sovos15** [comment]
Looking good on my end, i'll close it for now and reopen it if I see it again.
