### ISSUE TITLE
[Bug]: Broken drop in 2

### ISSUE THREAD

**Issue by sovos15** [civitai/civitai#1442]
### What happened?

https://github.com/user-attachments/assets/6503f561-61fc-412d-8b9a-10a46ed0c1fc

### Steps to reproduce the problem

1. Go to any dialogue box
2. Drag an image over it
3. Note the lines on the top or the bottom that indicate you can drop something there.
4. Try and be disappointed

### What should have happened?

There should not be drop in lines if there is no drop in option. 

### Additional information, context and logs

Bug reports will continue until morale improves

**Comment by manuelurenah** [comment]
This commit https://github.com/civitai/civitai/commit/6daddc05f10cf99c38481a6770780480db551725 should fix the issue. Thanks for reporting!
