### ISSUE TITLE
[Bug]: failed to create anything

### ISSUE THREAD

**Issue by VoidZero91** [civitai/civitai#1488]
### What happened?

Failed to create post
Invalid `prisma.post.create()` invocation: Error occurred during query execution: ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "25006", message: "cannot execute INSERT in a read-only transaction", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })

### Steps to reproduce the problem

post articles
update articles
post photos
update profile

### What should have happened?

the above message appears if i try to do anything

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

**Comment by manuelurenah** [comment]
Hey @VoidZero91 we were having some db issues earlier today, but we have since then resolved it. Hope this helps!
