### ISSUE TITLE
Issues with notifications creats a bad user experience on the site

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [civitai/civitai#150]
### Discussed in https://github.com/orgs/civitai/discussions/143

<div type='discussions-op-text'>

<sup>Originally posted by **a-l-e-x-d-s-9** January 12, 2023</sup>
1. People are adding responses to comments on my model, and I don't get any notification about it. I would like to have an option for notifications regarding all comments.
2. When people use a username or @ + username, it doesn't send me a notification.
3. When I leave a response to a comment, I don't get notifications about new comments on this thread.
All these notification problems create a lot of broken conversations, miscommunication, and misunderstandings. That leads to a generally bad experience on the site.
It would be great if you can address these issues, and fix them.
Thanks!</div>

**Comment by JustMaier** [comment]
I just added support for 1 and 3. They should be live later today. 2 is going to take some more time as we'll have to implement the ability to mention people in comments.

**Comment by a-l-e-x-d-s-9** [comment]
@JustMaier Thank you very much.

**Comment by JustMaier** [comment]
Hey, just wanted to let you know those new notifications are live 👍 
![image](https://user-images.githubusercontent.com/607609/212429070-f53a9e71-7b5e-4024-9380-8843ee7b9713.png)

We're working on the mention system now and hope to have it done early next week.

**Comment by a-l-e-x-d-s-9** [comment]
@JustMaier 
Seems to be working fine, but it popped-up 2 notifications for the same comment.
![image](https://user-images.githubusercontent.com/6518064/212495618-2ff724e3-d45b-4ade-a804-13985294bb08.png)

**Comment by JustMaier** [comment]
Just fixed this 👍

**Comment by a-l-e-x-d-s-9** [comment]
@JustMaier

1. The direct mention of a user with "@" seems to be working fine. I've received notifications.
2. If I drag the name of the user into the comment it only adds the link to his profile, but not adding a direct mention of him, and would not notify him, right? Can it be changed so that when dragging a username into a comment, it will automatically add "@" with all the direct mentioning functionality and notifications?
3. I just noticed a problem with notifications. A user commented on someone else review of my model, and I haven't received a notification. It should help you to debug the problem: [my model](https://civitai.com/models/2220/babes), [my username](https://civitai.com/user/alexds9), [review thread](https://civitai.com/models/2220/babes?modal=reviewThread&reviewId=6275), I haven't got a notification about a [comment from this user](https://civitai.com/user/Roodiee).
4. Suggestion: on most social platforms, the time of the comment is actually a direct link pointing to the comment itself. So you can copy, and paste it elsewhere for reference. Possibly point from one comment to information from another comment. It can be very useful.

**Comment by JustMaier** [comment]
@a-l-e-x-d-s-9 
1. Great
2. I haven't heard or seen the drag to mention functionality before. Is there a site that does it that way that I can test out to examine the interaction pattern?
3. Just found and squashed this bug as well.
4. Cool. I had never noticed that. We'll get that added 👍

**Comment by a-l-e-x-d-s-9** [comment]
Regarding my suggestion for a feature that dragging a username into a text would add "@" and the same functionality as direct mentioning, I couldn't find an example of a similar feature on Facebook, Twitter, or GitHub. Before you introduced the "reply" button, it was just something that I intuitively thought would work, and I tried to use it a few times. But never mind.

I have two suggestions regarding the "reply". Obviously, these two are not super important, and objectively not superior to the current configurations, just my suggestion for possible little improvements.
1. When you click on "reply" the @username will be added to the position of the cursor in the message and not at the beginning of the message. If you have not written anything, it will appear at the start of a new message. It's quality of life improvement, to address multiple people, point one person to another, and other cases.
2. The reply is on the bottom right of the message. Usually, it's far from the text and the username. It feels to me that it would be better positioned on the left of the emoji reaction, or to the right of the username - before the message.

**Comment by JustMaier** [comment]
1. Totally agree. I'd like to do it that way too. We had some trouble with the editor we're using and getting the mention to be injected at the position of the cursor. To get the mention feature out the door, I decided to just go with having it put the mention at the beginning of the message. I'll get this improvement on our todo list though.
2. What if we put it next to the reactions, similar to Youtube?
![image](https://user-images.githubusercontent.com/607609/213513255-506e98dc-e83b-4feb-9eb2-addfbbe06b4f.png)
![image](https://user-images.githubusercontent.com/607609/213513296-e44aa5f3-c1c1-42d5-8c0e-2aea75514b51.png)

**Comment by a-l-e-x-d-s-9** [comment]
Yeah, this position for reply probably would be better than the current position.

**Comment by a-l-e-x-d-s-9** [comment]
@JustMaier 
Are notifications not working after recovery from the latest hosting issues?
I haven't received a least one notification about [a new review](https://civitai.com/models/2220/babes?modal=reviewThread&reviewId=6700) of my model.

**Comment by JustMaier** [comment]
> Are notifications not working after recovery from the latest hosting issues?

It was actually something I broke when I revamped the model rank view yesterday. Should be fixed now. You might get those notifications now, if not, you will get them going forward.

**Comment by a-l-e-x-d-s-9** [comment]
@JustMaier 
Thank you very much.
Closing the issue.
