### ISSUE TITLE
[Bug]: Uploading model files to published models. Prisma update Unique constraint failed on the fields: (`modelVersionId`,`type`,`format`)

### ISSUE THREAD

**Issue by rockerBOO** [civitai/civitai#152]
### What happened?

I was adding a model file to a model version that was already created and set as published. A pruned model. But getting the following after saving the model.

Could not save model
Something went wrong: An error occurred while saving the model: Invalid `prisma.model.update()` invocation: Unique constraint failed on the fields: (`modelVersionId`,`type`,`format`)

### Steps to reproduce the problem

1. On a published model, upload a new model using +Add model under the model file on the edit model page. 
2. Wait for upload to finish and press save.

### What should have happened?

New added model file is uploaded and saved to the model and update the model version with the new pruned file.

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

I additionally tried to change the name of the model version but it did not change it. 

![Screenshot 2023-01-13 at 16-59-38 Civitai Share your models](https://user-images.githubusercontent.com/15027/212427138-5b123cf4-4be7-4581-b0eb-bc8b6eb234a8.png)

**Comment by JustMaier** [comment]
We really should improve that message. Sorry about that.

It's complaining because you have two "model" type files with the same format, "safetensors". In this scenario, it looks like you probably meant to attach a "Pruned Model" type file.

I apologize for the confusion and inconvenience, and I'll dig into this to see if there is a way we can make it more clear.

**Comment by rockerBOO** [comment]
Ok fair enough :). 

My opinion on this situation is the error could be better, but the problem was doing this in the first place. I was mistaken in using model (since I could pick it) and start uploading my file (with extension as safetensors) where it should detect this problem.

I did spend some time looking around the UI for info, but all you have is those + parts there, not knowing what they are for exactly in terms of the site. A model or pruned model are basically the same thing, except if you do ema pruning (which is what I was assuming it meant) vs fp32 to fp16 model shrinking. 

I would propose a page that goes into details, also including the thing you said about 1 model format in each format (safetensors/ckpt). This would just clarify these details before the user spends time uploading something that will just need to be re-uploaded. Also, probably save on orphaned files if not already.

I'm grateful for the platform and the work put into it, my opinions and suggestions are just those. I do not expect anything, so no worries.
