### ISSUE TITLE
[Bug]: Editing a comment clears out mention linking

### ISSUE THREAD

**Issue by rockerBOO** [civitai/civitai#158]
### What happened?

When editing a comment, the link to the mentioned user is removed. 

### Steps to reproduce the problem

1. Make a comment and mention someone
2. Edit comment
3. Save edit comment

### What should have happened?

Link should remain after editing

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

Just noticed it and know it's a new feature but wanted to mention it.

**Comment by JustMaier** [comment]
@manuelurenah can you help with this one when you have a few minutes?
