### ISSUE TITLE
[Bug]: GitHub sign in redirects to localhost

### ISSUE THREAD

**Issue by evgenykochetkov** [civitai/civitai#186]
### What happened?

Tried to sign in using GitHub, got redirected to http://localhost:3000/api/auth/callback/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=REDACTED

### Steps to reproduce the problem

1. Go to https://civitai.com/login
2. Press "GitHub"

### What should have happened?

A successful sign-in.

**Comment by JustMaier** [comment]
Fixed. Sorry about that. Looks like the GitHub oAuth tokens weren't quite right after our server migration 2 days ago.
Thanks for the heads up.
