### ISSUE TITLE
[Bug]: Not possible to use api to download "early access" models via api

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#240]
### What happened?

I signed up to be a member today, and noticed my code to the API bonked with the new membership thing.  Is there and API update that let's me log in as a member to download the "early access" models via the API?

### Steps to reproduce the problem

trying to download the model api link yields an html file asking to be a member, I am a member but have no way of telling the api that.

### What should have happened?

the early access model should be downloaded

### What platforms do you use to access the site?

Windows

**Comment by JustMaier** [comment]
Hey @RandomInternetPreson we've just finished adding API keys to the tool. You should now be able to generate an API Key from your account page.
![image](https://user-images.githubusercontent.com/607609/218338508-b7528e14-c04d-482e-a10d-cecba7a86828.png)

You can then use the key when requesting the download to get early access files, like this:
```
https://civitai.com/api/download/models/1144?token={yourAPIKeyHere}
```

Alternatively, if you're making the request from an environment that allows you to set headers, you could also include the token as a Bearer token in the Authorization header:
```
Authorization: Bearer {yourAPIKeyHere}
```

**Comment by RandomInternetPreson** [comment]
Thank you, the api key is working as advertised :3
