### ISSUE TITLE
[Bug]: There are many models that are not showing up in the api response when sorting by new

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#259]
### What happened?

If I send a request for the newest 100 uploads (https://civitai.com/api/v1/models?limit=100&sort=Newest) I do not see several uploads that should be in the list.

For example at the time of this writing none of the models from:
https://civitai.com/user/bloodsplash09
https://civitai.com/user/Puffin

show up in the api response

### Steps to reproduce the problem

go here: (https://civitai.com/api/v1/models?limit=100&sort=Newest

you should see models from:
https://civitai.com/user/bloodsplash09
https://civitai.com/user/Puffin

but you don't see any of these models in the api response, even though they are showing on the civitai site.

### What should have happened?

new models should be showing up in the api call for the newest 100 uploads, but there are several missing and they look to be missing as a function of the person uploading them, that is that the missing models from the api call are not random they are from certain uploaders

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

I use the api a lot, and have never seen this happen before.

**Comment by JustMaier** [comment]
This should be fixed now. We updated the name of an environment variable that controlled the visibility of NSFW models to unauthenticated users and failed to update the name in production 😬 

Should be back to normal now 👍

**Comment by RandomInternetPreson** [comment]
Yup looking good now :3
