### ISSUE TITLE
[Bug]: All models filtered out when browsing while logged in

### ISSUE THREAD

**Issue by Machinekng** [civitai/civitai#269]
### What happened?

Yesterday, I noticed that all models are filtered out when I am browsing while logged in. This is true on the main page, as well as my liked models page and any user pages. The exception is the hidden models page, where I can still see the (faded) list of hidden models.

This issue affects me when logged in on multiple browsers, but not when logged out. If I have the model page link, I can still go to the page and interact with it, only search is impaired.

### Steps to reproduce the problem

1. I logged in, and went to the main page, removing all filters. I get the no results found icon.
2. I log out, and the search works fine.
3. I made a burner account to see if it was a system/browser issue, but I the new account works fine.
4. I attempted other troubleshooting steps as well (clearing cookies, disabling browser extensions, etc..)

### What should have happened?

I just want to restore normal account behavior. It's strange that it seems to be account specific. My guess is that I triggered a bug when switching a few user settings in rapid combination that corrupted some user setting. I'm okay if you need to reset my account: I can rebuild my likes/hidden settings, but just want to keep the supporter badge.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome

**Comment by manuelurenah** [comment]
Hey @Machinekng, is this still an issue you are experiencing? Sharing screenshots or screen recording might help us identify your the problem. I'd appreciate if you share with us your user account as well to have a deeper look into it. Thanks!

**Comment by Machinekng** [comment]
Of course. The account on civitai is also machinekng.

This is what it looks like when I am logged in:

![image](https://user-images.githubusercontent.com/8943264/219977689-cad53ad4-a01e-4830-8346-b26124e3136e.png)

This is what it looks like when I am logged out:

![image](https://user-images.githubusercontent.com/8943264/219977734-1849056f-3231-44c8-a638-30276703b65c.png)

**Comment by nvmmonkey** [comment]
<img width="1412" alt="截屏2023-02-21 23 40 24" src="https://user-images.githubusercontent.com/100928742/220390957-fde3ea57-dcc2-4e5e-a23b-0b8ef0912811.png">
Yah, i cannot search for a specific model anymore, this greatly affect some abilities using sd-civitai-brower on webui from here. https://github.com/camenduru/sd-civitai-browser

**Comment by Machinekng** [comment]
> <img alt="截屏2023-02-21 23 40 24" width="1412" src="https://user-images.githubusercontent.com/100928742/220390957-fde3ea57-dcc2-4e5e-a23b-0b8ef0912811.png">
> Yah, i cannot search for a specific model anymore, this greatly affect some abilities using sd-civitai-brower on webui from here. https://github.com/camenduru/sd-civitai-browser

Yeah, looks like the site is effectively down right now. I can't search or even log in.

**Comment by ZhaoYunxiong** [comment]
I have the same problem

**Comment by Squibeel** [comment]
This always happens to me after I've hidden an X amount of models. Not sure if it's the cause.

**Comment by Machinekng** [comment]
> This always happens to me after I've hidden an X amount of models. Not sure if it's the cause.

I do have a lot of models hidden, and now that you mention it, the issue could have cropped up when I was hiding models.

Were you able to fix the issue by unhiding models?

**Comment by Machinekng** [comment]
I unhide all the users I was currently hiding (170+ users) and some additional models and search is now working again.

I think that means this is a bug with the hidden model filter?

**Comment by Machinekng** [comment]
Another update, I tried hiding by tag instead of user/model, and the issue came up again once I added enough tags. I removed a few, and search is working.

**Comment by Squibeel** [comment]
> > This always happens to me after I've hidden an X amount of models. Not sure if it's the cause.
> 
> I do have a lot of models hidden, and now that you mention it, the issue could have cropped up when I was hiding models.
> 
> Were you able to fix the issue by unhiding models?

Short of deleting the account and starting over I never found a solution for it.
In the end I stopped hiding models. Unfortunatly the Everything filter isn't showing up Adult results now so that's another issue.

**Comment by manuelurenah** [comment]
@Machinekng thanks for sharing that information. That's pretty crucial to get to the root cause of this problem. I'll be making some tests to see if I'm able to reproduce the issue and come up with a solution for it

**Comment by Janonas** [comment]
Ill add that for me it only seems to affect some models?

**Comment by Machinekng** [comment]
> Ill add that for me it only seems to affect some models?

That's probably unrelated to the hidden model bug, especially as there was recently a purge of TOS-violating models.

**Comment by Janonas** [comment]
> > Ill add that for me it only seems to affect some models?
> 
> That's probably unrelated to the hidden model bug, especially as there was recently a purge of TOS-violating models.

Nah i figured out later that it was any NSFW model for me, even with the option enabled

**Comment by manuelurenah** [comment]
With our latest release, this should be resolved now. Please let us now if you are still experiencing issues when filtering models or excluding tags/users/models.

**Comment by namelessentity** [comment]
No, I'm having this issue here too. But, only on desktop. As a test I tried on my phone, everything shows. But I'm not about to be downloading this sort of thing on my phone.

I have a bunch of models liked, I've never blocked a model, and I have no models uploaded. It happens for all models, adult or not.

**Comment by ZLTM** [comment]
same issue here, any fix, please? I see this was reported in February...

**Comment by ZLTM** [comment]
fixed as soon as i commented, to anyone wondering it seems Civit will do this when its down, so if its happening to you maybe you just need to wait it out

**Comment by Squibeel** [comment]
It does seem to be happening again. Can only see models with the Everything browsing mode turned on atm.

**Comment by FatalPK** [comment]
its 2024 now and I just created an account, I am having the exact same issue and its just after creating an account. Was there ever a definite fix for this issue? or are we just not able to use the account? Absolutely no search results are popping up for me on my MacBook or my phone after logging into my account.

**Comment by DataJuggler** [comment]
I am getting this today. I don't see any models if you click on the Models tab.

**Comment by Razor20** [comment]
Encountering the same issue here as well 🫤
