### ISSUE TITLE
not found: Can't resolve 'use-sync-external-store/shim' 

### ISSUE THREAD

**Issue by qiuguian** [civitai/civitai#270]
### What happened?

odule not found: Can't resolve 'use-sync-external-store/shim'

Import trace for requested module:
./node_modules/_use-sync-external-store@1.2.0@use-sync-external-store/shim/with-selector.js
./node_modules/_zustand@4.3.3@zustand/esm/index.mjs
./src/store/ClientHistoryStore.tsx
./src/pages/_app.tsx

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

npm run dev  error : not found: Can't resolve 'use-sync-external-store/shim'

**Comment by manuelurenah** [comment]
Hey @qiuguian! Not sure what you meant by opening this issue, are you trying to run the whole project in your own machine?
