### ISSUE TITLE
[Bug]: Adult Models Vanished Across the entire Site

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#275]
### What happened?

There are no adult models visible on Civitai, even when you have adult models active. On my model list, if adult models are active, *none* of my models show. If I disable it, only my safe models show. But with it active, everything of mine is hidden with:

```
No results found
Try adjusting your search or filters to find what you're looking for
```

### Steps to reproduce the problem

1. Browser civitai or
2. Visit your profile and personal models (if you have NSFW models)
3. Notice you have no results found.
4. Disable NSFW and only your safe models show, but no longer receive no results found error. 

### What should have happened?

I can see adult models site-wide with my appropriate settings. 

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by WASasquatch** [comment]
Additionally, new models posted that are adult, are not being shown to anyone else as well, doesn't exist for them on my profile or anything: https://civitai.com/models/11146/was-meredith-stout

**Comment by manuelurenah** [comment]
Hey @WASasquatch! We did a release recently which should have fixed this issue. Can you please confirm this is not happening for you anymore?

**Comment by WASasquatch** [comment]
> Hey @WASasquatch! We did a release recently which should have fixed this issue. Can you please confirm this is not happening for you anymore?

They're all showing now! Awesome job guys!
