### ISSUE TITLE
[Bug]: Page over burdened

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#283]
### What happened?

Suddenly Civitai is overburdened with a lot of jank time, and slow loading. Additionally, scrolling is no longer smooth. It's very jerky/stuttery. 

Checking online, the site gets a performance score of C or D (and fluctuating, whether server performance or scripting performance), which ain't good. 

One of the biggest factors is the image delivery. It's using cookies, which is unnecessary traffic as the server will ignore them. Need a proper CDN or a subdomain distributor that is cookie-free. 

Setup:
Core i9 13900KF (Up to 5.8Ghz Boost)
32GB 5600MHz DDR5
SN570 NVMe 1TB (OS Drive)

### Steps to reproduce the problem

1. Visit the site

### What should have happened?

Site should be much more responsive and smooth.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

Thins were smooth yesterday, despite all the downtime. 🤷

**Comment by manuelurenah** [comment]
Hey @WASasquatch Thank you for taking the time filing this issue. I was experiencing the same behavior you mentioned yesterday, but it's not happening anymore. Can you please confirm site is loading okay for you now?

**Comment by WASasquatch** [comment]
Yeah it seems things are fixed now. Page scrolls smoothly. There is still a lot of initial jank on page load. On my machine it uses a lot of resources initially, I'm not sure if that's just cause my machine has the resources to spare, or if it's really wanting that sort of environment. If that is the case though it could hit mobile devices or weak computers with less RAM pretty hard or crash the device. 

That all being said, at least most people utilizing these are on decent systems aside from the colab users. 

But perhaps the modules could be spaced out a bit in their initialization on page load. It seems they're all being thrown at the the browser at once.
