### ISSUE TITLE
[Bug]: Paged Image Galleries Broken

### ISSUE THREAD

**Issue by Kittera** [civitai/civitai#287]
### What happened?

After the most recent outage, it seems like the ability to page through a gallery of images from either the model page itself or from one of its reviews is gone. Only one image can be viewed at a time, to view another one must exit that image and click another. There is no "page indicator" at the bottom, left/right arrows don't work, 

### Steps to reproduce the problem

-Click on an image from any model or model review with multiple images.
-Attempt to scroll left or right through the image gallery

### What should have happened?

When viewing an image fullscreen, it should have the page indicator dots and it should show clickable left/right arrows as well as respond to left/right arrow key inputs.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by manuelurenah** [comment]
Hey @Kittera we were experiencing some issues with our cdn provider yesterday and that could have been causing this issue for you. Can you please confirm this is not happening for you anymore?

**Comment by JohnMadden123456** [comment]
@Kittera I reported similar issue on discord. It only affects NSFW images. Galleries show SFW images same as before, but all NSFW images are excluded and show 1 image in gallery. Either in model, or in comments. I.e. when model/comment have 5 images, but 2 of them are NSFW, it will show list of 3 images in gallery. 

Still seeing this problem guess I need to wait for CDN near me to be updated.

Is it the same for you? Can you test on NSFW model with NSFW images?

**Comment by JohnMadden123456** [comment]
Yay, it is fixed now. I guess this was an issue and not a CDN https://github.com/civitai/civitai/commit/f652e3e3626c8ffb52147c8e933d996a3b9a933d

**Comment by manuelurenah** [comment]
> Yay, it is fixed now. I guess this was an issue and not a CDN [f652e3e](https://github.com/civitai/civitai/commit/f652e3e3626c8ffb52147c8e933d996a3b9a933d)

@JohnMadden123456 This has been fixed as @JohnMadden123456 pointed out
