### ISSUE TITLE
[Bug]: Page element layout

### ISSUE THREAD

**Issue by timelic** [civitai/civitai#302]
### What happened?

<img width="1178" alt="截屏2023-02-27 17 40 07" src="https://user-images.githubusercontent.com/20257354/221528283-b29794e5-6bc4-4047-bfb7-a7dbfd2725fa.png">

This screenshot is from https://civitai.com/models/13256/boneless-pizza. The carousel component on the left is not  vertically centered, and the controller is not vertically centered either. These make the whole page look unbalanced.

### Steps to reproduce the problem

https://civitai.com/models/13256/boneless-pizza

This occurs when the aspect ratio of the preview images are all greater than one.

### What should have happened?

<img width="1180" alt="截屏2023-02-27 17 45 42" src="https://user-images.githubusercontent.com/20257354/221529586-15a050a8-6e4c-4d56-acb9-6b55a9fb6fda.png">

This layout may be better.

### What platforms do you use to access the site?

Windows, MacOS

### What browsers do you use to access the site?

Google Chrome

**Comment by WASasquatch** [comment]
I'd rather see a fixed portrait size, and just zoom in the landscape scaled images to fit, so the space is completely occupied. Civit AI has a lot of dead space on my resolution, which is basically substandard now (1080p).

**Comment by timelic** [comment]
> I'd rather see a fixed portrait size, and just zoom in the landscape scaled images to fit (click to view full size), so the space is completely occupied. Civit AI has a lot of dead space on my resolution, which is basically substandard now (1080p).
> 
> Landscape images always get so tiny in these flex/column style galleries. Which is often odd when the images are often larger in most galleries and like wallpapers and such.

Yep, the page style needs to be fine-tuned
