### ISSUE TITLE
[Bug]: Wrong data in search result

### ISSUE THREAD

**Issue by zyd232** [civitai/civitai#312]
### What happened?

The data of some objects are not correctly shown in search result. As shown in the following screenshots:

![incorrect data in search result](https://user-images.githubusercontent.com/8241783/222157470-40848820-83e9-4e30-982d-871d406414ef.png)
![correct data](https://user-images.githubusercontent.com/8241783/222157562-992c00ef-b8b6-4bf1-86b4-10f3cb8762bd.png)

This issue is not only about this object, but also can be found on other objects. 

### Steps to reproduce the problem

1. Search "zyd232's Chinese Girl LORA" on civitai.com
2. Check the data about downloads, likes and comments on the card.
3. Click the card to enter the detail page. Check the data about downloads, likes and comments in the detail page.
4. You can find the data in step 2 and step 3 are not the same.

### What should have happened?

The data in search result should be the same as the data in detail page.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Microsoft Edge

**Comment by manuelurenah** [comment]
Hey @zyd232 we had a small downtime which caused items in your home feed to be out of sync from the actual metrics. It should be okay now
