### ISSUE TITLE
[Bug]: OpenGraph description preview has no spaces for new lines, results appear aweful. 

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#314]
### What happened?

The OpenGraph data for models and such is pretty bad. It doesn't have spaces for new lines, so they are back to back with a often different paragraph. 

![Screenshot_2](https://user-images.githubusercontent.com/1151589/222223699-957770d5-5380-4a26-8016-530bf6d866c5.png)

Perhaps new lines should be prefixed with ` | ` or just a space, though a space may confuse people when it is a new paragraph/subject. 

### Steps to reproduce the problem

1. Post content from CivitAI anywhere with OpenGraph support, with a formatted description area. 

### What should have happened?

N/A

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by JustMaier** [comment]
Thanks for calling this out. It was bugging me too. All of the model descriptions are stored in HTML so we had a tag stripping function that wasn't good about mantaining spaces when it needed to. I've updated that so now it should look a little better. Optimally we'll store two versions of the description in the future, one with tags, and one without.
