### ISSUE TITLE
[Bug]: The upload of the picture failed, the preview code found that the sub -thread started failed

### ISSUE THREAD

**Issue by ChengJiuSu** [civitai/civitai#318]
### What happened?

Drag Images Here or CLICK to Select Files, I have always uploaded no error information output.

### Steps to reproduce the problem

Drag Images Here or CLICK to Select Files, I have always uploaded no error information output
Picture upload failed

### What should have happened?

Normal should be displayed or successful

### Additional information, context and logs

![企业微信截图_16777604506893](https://user-images.githubusercontent.com/108964694/222431183-6c103a1b-e033-4a5d-9ef2-2aa6c33c7335.png)

**Comment by JustMaier** [comment]
We believe we've resolved the issue related to this. Can you let us know if you're still experiencing this issue?

**Comment by ChengJiuSu** [comment]
At present, I found that there is no trigger to the upload interface after entering the sub -thread. It feels like it has not successfully entered the sub -thread stage. There is no error or successful output.

**Comment by WASasquatch** [comment]
> We believe we've resolved the issue related to this. Can you let us know if you're still experiencing this issue?

I am still getting dead uploads on submission, that show uploaded, and display on the edit page.

**Comment by RayHell** [comment]
I am still experiencing the issue on my end. Stuck at warming up.

**Comment by JustMaier** [comment]
We'll be replacing the client-side image processing pipeline soon which should make this set of issues go away.

**Comment by manuelurenah** [comment]
With the new model creation process, this should be fixed by now. Please let us know if you're still facing issues when uploading images
