### ISSUE TITLE
[Bug]: API: Models Type parameter doesn't work

### ISSUE THREAD

**Issue by Hugo-Matias** [civitai/civitai#323]
### What happened?

Calling the /models endpoint with the type parameter doesn't seem to make a difference regardless of the enum type chosen.

### Steps to reproduce the problem

The response from the following url will return 3 Checkpoints:

[https://civitai.com/api/v1/models?limit=3&type=TextualInversion](https://civitai.com/api/v1/models?limit=3&type=TextualInversion)

That's a link taken from the wiki and it also exhibits this problem in the documented response [example](https://github.com/civitai/civitai/wiki/REST-API-Reference#example-1).

This seems to be happening with the other options as well.

### What should have happened?

The Type enum values should return their corresponding model types.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by JustMaier** [comment]
Thanks for calling this out. I noticed it myself a while back and forgot to update the wiki. The url should be `https://civitai.com/api/v1/models?limit=3&types=TextualInversion`

I've now updated the wiki so that hopefully more people don't stumble on this.
