### ISSUE TITLE
[Bug]: API by-hash is returning 404's for valid hashes.

### ISSUE THREAD

**Issue by dsully** [civitai/civitai#365]
### What happened?

The API is returning a 404 error for valid hashes. Tried with blake3 and sha256 copied from model pages.

### Steps to reproduce the problem

For example, using the blake3 hash copied from Dreamshaper's model page for the `3.31 bake vae` version:

https://civitai.com/models/4384/dreamshaper

Which is: `30BE3842DAE0A525F6BF47A1E1B47098AEA72500553B77541885F497C1D03723`

```
$ curl --head -X GET https://civitai.com/api/v1/models-versions/by-hash/30BE3842DAE0A525F6BF47A1E1B47098AEA72500553B77541885F497C1D03723
HTTP/2 404
date: Sun, 12 Mar 2023 03:06:30 GMT
content-type: text/html; charset=utf-8
x-powered-by: Next.js
cache-control: private, no-cache, no-store, max-age=0, must-revalidate
vary: Accept-Encoding
strict-transport-security: max-age=15724800; includeSubDomains
cf-cache-status: DYNAMIC
server-timing: cf-q-config;dur=6.9999950937927e-06
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=YBenzlVU0DdR4pPlK%2Bvxn%2BeDxCuVxZOZei%2B1Z%2FlpSrF9o4sLoS7hBHr8gWIIL1f0wbV1b5qrbMGImqG49hE2poe%2BU4Tgruvyw6EwIx05iXp0Fq7KDbNnLcA6dOmAXscpD7LtjA4HrqsLzg%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7a68d2552bb89836-SJC
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

### What should have happened?

A valid model JSON response should be sent.

### What platforms do you use to access the site?

MacOS

### What browsers do you use to access the site?

Apple Safari

**Comment by JustMaier** [comment]
Looks like you've got a small typo in your request url. It should be:
```
https://civitai.com/api/v1/model-versions/by-hash/30BE3842DAE0A525F6BF47A1E1B47098AEA72500553B77541885F497C1D03723
```

You had `models-versions` instead of `model-versions`

**Comment by dsully** [comment]
Derp. Thank you.

**Comment by JustMaier** [comment]
Happens to the best of us 😛
