### ISSUE TITLE
[Bug]: Reporting broken

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#368]
### What happened?

Reporting is broken

```
Unable to send report
Invalid `prisma.commentReport.create()` invocation: An operation failed because it depends on one or more records that were required but not found. No 'Comment' record(s) (needed to inline the relation on 'CommentReport' record(s)) was found for a nested connect on one-to-many relation 'CommentToCommentReport'.
```

### Steps to reproduce the problem

1. Go to comment/model/etc (specifically image comment)
2. Report it

### What should have happened?

Report content

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by JustMaier** [comment]
I'm having trouble reproducing this.

I was able to successfully report the following:
- Model
- Image
- Comment on Model
- Comment on Image.

Do you have a specific comment I should try to report?

**Comment by JustMaier** [comment]
Ok, we found this issue and fixed this.

Thanks for the bug report @WASasquatch!
