### ISSUE TITLE
[Bug]: Model information jumps location in prompt information modal

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#369]
### What happened?

The location of the model used in a generation changes location between images _seemingly by random_ between images. 

I guess differences in template files or something? 

![Screenshot_8](https://user-images.githubusercontent.com/1151589/224912838-02e54b1d-56be-46b2-9196-d06c6f7a0048.png)
![Screenshot_9](https://user-images.githubusercontent.com/1151589/224912860-0e6ab352-d178-4069-9293-3436e6ded328.png)

### Steps to reproduce the problem

1. Go to model and view image prompt details
2. Certain images, the model data location changes

### What should have happened?

A consistent layout design for referencing data between images.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

Just a minor design issue

**Comment by JustMaier** [comment]
We were trying to be smart about displaying the Model name in a one-line box or half line box based on the length of the model name. End result was it switching between those positions you showed. I've made it so that it always uses the one-line box,
