### ISSUE TITLE
[Bug]: Landscape format images have blurry thumbnails

### ISSUE THREAD

**Issue by Letiliel** [civitai/civitai#375]
### What happened?

I uploaded images for model reviews and all 16:9 ones get blurry thumbnails.
From looking at other images it seems the wider the image, the blurrier the thumbnail.

### Steps to reproduce the problem

Check the reviews on this model's page for example : [https://civitai.com/models/7241/mix-pro-v3](url)
Look closely, some thumbnails are sharp, others are a bit or quite blurry.

### What should have happened?

--

**Comment by WASasquatch** [comment]
No blur here.

**Comment by JustMaier** [comment]
> From looking at other images it seems the wider the image, the blurrier the thumbnail.

We use scaling within Cloudflare Images to size everything down to 400px wide inside the review preview carousels, they then get scaled down further by your browser to 300px min based on how many review tiles we're showing. There are a few things that could be happening here:
1. Really wide images scaling down to 400px might lose detail
2. The browser isn't scaling 400px to 300px appropriately

Either way, when I browse that page I don't see anything particularly blurry, would you mind sharing a few screenshots so I can make more sense of how blurry you mean?

**Comment by Letiliel** [comment]
![blur](https://user-images.githubusercontent.com/4447503/226213950-0b51c292-766e-45ca-9437-dfa56369f7ae.png)
Here the top one is blurry, the bottom one is sharp.

And I know what's happening : the images get resized to 400px width as you said, then they get displayed as croped squares of 400*400. So for landscape ratio images, since their height is less than 400px after the resize, the actually get zoomed in to fit in the 400px height. And zoomed in means blurry.

Solution: resize landscape ratio images to 400px *height* not width

**Comment by WASasquatch** [comment]
Honestly images should be 2-4x the actual viewing size for retina displays. Using AVIF will cut out on size substantially. We're long past the ages of 64k dialup and needing such tiny images.

**Comment by manuelurenah** [comment]
Hey all, with the newest release on Civitai, this should have been sorted out. Please let us know if there are any issues with it again
