### ISSUE TITLE
[Bug]: Download Total Random

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#376]
### What happened?

The total downloads are seemingly random, and do not reflect the project.

For example, I have 743 total downloads, but the total only reads a random 293

https://civitai.com/models/20793/was-node-suites-comfyui

### Steps to reproduce the problem

1. Go to model with multiple version
2. Count the total downloads of all versions
3. Refer to the total downloads at the top of the page. ***It doesn't relate to any one version, or the total.***

### What should have happened?

Simply count up all versions downloads. No funny business. 

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by JustMaier** [comment]
Looks like we were missing some lines in the metric updating system when we turned unique download tracking back on. It's been fixed now and the change it being deployed now.

**Comment by JustMaier** [comment]
This should be resolved now. Last I checked your model now has 850 downloads.

**Comment by WASasquatch** [comment]
Awesome work. I probably would have never noticed if I didn't have so many files in there.
