### ISSUE TITLE
[Bug]: db:migrate failed

### ISSUE THREAD

**Issue by MacBlackCat** [civitai/civitai#380]
### What happened?

```
db error: ERROR: cannot alter type of a column used by a view or rule
DETAIL: rule _RETURN on view "ImageResourceHelper" depends on column "name"
   0: sql_migration_connector::validate_migrations
           with namespaces=None
             at migration-engine\connectors\sql-migration-connector\src\lib.rs:301
   1: migration_core::state::DevDiagnostic
             at migration-engine\core\src\state.rs:269
```

Happening after a fresh clone of main branch and following the steps described in the readme. 
Step 5 is where it fails. Ive never worked with this db framework so no idea whats going wrong here.
Is there a faulty config/file on my side or something with repo?

### Steps to reproduce the problem

Follow the readme steps till step 5.

### What should have happened?

Succesful migration.

**Comment by manuelurenah** [comment]
There were some bad migrations in the main branch, but we pushed new changes recently which fixes the issue. Please pull latest from main and try again.
