### ISSUE TITLE
[Bug]: Discussion section is disappearing on scroll after expanding a long model description 

### ISSUE THREAD

**Issue by NoCrypt** [civitai/civitai#395]
### What happened?

The discussions and reviews is disappearing on scroll after expanding a long model description, it seems like there's a problem with Intersection Observer. For more details, watch video below

https://user-images.githubusercontent.com/57245077/227829566-a05ebe30-1b12-4147-9c70-43f1bfd26249.mp4

### Steps to reproduce the problem

1. Go to any model page that have a long model description ([like this one](https://civitai.com/models/22530))
2. Press `Show More` in model description
3. Scroll down to discussion/review section

### What should have happened?

Discussion/review section should be visible all the time regardless on how long the model description is

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

**Comment by MrRace** [comment]
Why can't I open the website https://civitai.com/ ?

**Comment by manuelurenah** [comment]
This has been fixed in the latest release
