### ISSUE TITLE
Can't enable mature content

### ISSUE THREAD

**Issue by Ouinon0** [civitai/civitai#397]
### What happened?

When I'm going into the settings I can enable mature content. But once the option is enable it will not save it, so each time I reload or close the page I will always get a home page without nsfw. 

### Steps to reproduce the problem

1. Go to settings
2. Enable mature content
3. Reload the page

### What should have happened?

It must save what I've select

### What platforms do you use to access the site?

Windows, Linux, MacOS, iOS, Android, Other/Cloud

### What browsers do you use to access the site?

Mozilla Firefox, Brave, Apple Safari

**Comment by shahovkit** [comment]
Same problem for me
