### ISSUE TITLE
[Bug]: Issue Creating Account with Reddit

### ISSUE THREAD

**Issue by Ijee** [civitai/civitai#405]
### What happened?

I just created a new account on civitai.com two days ago through Reddit as a third party authentication which initially worked and I gave access to the information  requested which lead me back to the main page of the civitai website. 
There everything worked initally until this popup came up every other page reload with an overlay blocking clicking on anything else and could not be closed.
![image](https://user-images.githubusercontent.com/15277745/228775496-968ff5ac-e13e-4da7-a4c1-f52ec2bbff53.png)
A day after that I am now stuck on a page which shows the following with no way getting through this page because of the content missing entirely in the dom:
![image](https://user-images.githubusercontent.com/15277745/228776034-671bfb1c-8471-40f6-88a1-9457d96cf1f5.png)

I feel like this has something to do with the nsfw filter because when I first tried turning it on I got an error which I did not screenshot and I could also not set a user name on the settings page which threw an error saying it was missing certain fields which looked like a JSON response - sorry that I do not have the exact words/screenshot there.

If you guys need my account information I'll provide them privately so you can check logs, etc.

All of this was the case with and without ad-blocker / umatrix.

### Steps to reproduce the problem

1. Go to civitai.com and sign up with the third party Reddit.
2. Grant access to share account details.
3. Go to the settings page and enable NSFW content

### What should have happened?

Either I should have gotten a prompt to provide additional information or a way to re-do the activation process.
Not entirely sure what the best way to handle this would be.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome

**Comment by JustMaier** [comment]
This should be resolved now. Feel free to re-open this issue if you're still having trouble 👍

**Comment by Ijee** [comment]
Thanks for the swift fix. 👍
