### ISSUE TITLE
[Bug]: Image links missing from Json file downloaded from API

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#414]
### What happened?

Each of the posts usually has a set of links, one for each image.  The links reside in the response.items.modelVersions.images part of the structure downloaded from the API. 

Now all of the .images parts of the Json file are empty.

### Steps to reproduce the problem

Go here: https://civitai.com/api/v1/models?limit=100&sort=Newest

Download the json file, there are no more links to images 

### What should have happened?

There should be links to all the images for a particular post.  The .images variable is still there, it's just empty.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

**Comment by faded-lov** [comment]
I found the same problem, at the same time, I found that now the picture information is obtained by the new link  (https://civitai.com/api/trpc/image.getImagesAsPostsInfinite?input=...). Is there any description of this api?
