### ISSUE TITLE
[Bug]: Indexing problems

### ISSUE THREAD

**Issue by remixer-dec** [civitai/civitai#417]
### What happened?

Some models are not always indexed and cannot be found through search

### Steps to reproduce the problem

1. Go to https://civitai.com/?query=doge or https://civitai.com/tag/doge in incognito mode
2. See only 1 textual inversion (or nothing for a tag)

### What should have happened?

At least 2 loras with this tag + title exist

**Comment by remixer-dec** [comment]
Also just noticed that the tag page title is "undefined"

**Comment by JustMaier** [comment]
Hey my Doge pal, it looks like as part of the default filters we were hiding resources tagged with the `meme` tag which two of those doge resources had. I've removed that tag from the hidden tags and now they're showing up as expected.

As for the "Undefined" thing in the title. Yeah... We need to fix that. I'll leave this open until we've got that fix in place.

**Comment by manuelurenah** [comment]
The fix for the tag page is queued for our next release

**Comment by remixer-dec** [comment]
Alright, thank you!
