### ISSUE TITLE
[Bug]: The API has died :c

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#421]
### What happened?

going here https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1

yields: {"message":"An unexpected error occurred","error":{}}

### Steps to reproduce the problem

go here: https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1

you will not get a Json file response from the API

### What should have happened?

I should have gotten a Json file.

**Comment by AugmentedRealityCat** [comment]
When I try to scan the models using the civitai extension I get this error message directly from the GUI
`Connect to Civitai API service failed. Wait a while and try again, check console log for detail`

Here is what the log is saying when you try to connect to the API with the Civitai extension for A1111:

```
Civitai Helper: Start scan_model
Civitai Helper: Scanning path: C:\stable-diffusion-webui\embeddings
Civitai Helper: Creating model info for: 16-token-negative-deliberate-neg.pt
Civitai Helper: Use Memory Optimized SHA256
Civitai Helper: sha256: ec6a52b7f30d79d52dd347acbb1de45032fa0597d7e73c3e54bc7379b023334b
Civitai Helper: length: 50206
Civitai Helper: Request model info from civitai
Civitai Helper: Get error code: 500
Civitai Helper: Internal Server Error
Civitai Helper: Delay 1 second for TI
Civitai Helper: Connect to Civitai API service failed. Wait a while and try again
```
I tried again many times, to no avail.
The civitai website itself is responding.
Error 500 usually indicates a generic internal server error.
One clue is that the page related to the extension is not working properly, and it displays this message:
`Application error: a client-side exception has occurred (see the browser console for more information).`

So, I did exactly that, and here is what the Firefox browser console had to say:
```
oss-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://static.cloudflareinsights.com/beacon.min.js/vb26e4fa9e5134444860be286fd8771851679335129114. (Reason: CORS request did not succeed). Status code: (null).

None of the "sha512" hashes in the integrity attribute match the content of the subresource. [civitai-helper-sd-webui-civitai-extension](https://civitai.com/models/16768/civitai-helper-sd-webui-civitai-extension)
Loading failed for the <script> with source “https://analytics.civitai.com/js/plausible.js”.
```

**Comment by wacdev** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/127726508/229971246-13c161c6-8b08-424d-a1b7-0dcf0275a7d3.png">

**Comment by JustMaier** [comment]
This should be resolved now. Feel free to reopen the issue if you continue to have trouble.
