### ISSUE TITLE
[Bug]: Tag page url not properly encoding special characters when selected from dropdown in search bar

### ISSUE THREAD

**Issue by knzro** [civitai/civitai#423]
### What happened?

When an user seaches for a tag that includes special characters and selects it from the dropdown, the resulting url is not properly encoded.

### Steps to reproduce the problem

1. Go to civitai main page
2. search for Ranma 1/2
3. select #Ranma 1/2 from the recomended results

### What should have happened?

The page it opens is: https://civitai.com/tag/ranma%201/2
It should instead be: https://civitai.com/tag/ranma%201%2f2
![image](https://user-images.githubusercontent.com/83365874/230151304-7138c133-b527-4782-8fbd-284a3e8517f6.png)
![image](https://user-images.githubusercontent.com/83365874/230151461-58bb92d5-8a4a-4ca3-a36c-fbfacba80ff4.png)

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by bkdiehl** [comment]
Thanks for spotting this. Fix will be out soon.

**Comment by manuelurenah** [comment]
Closing since this has been fixed
