### ISSUE TITLE
[Bug]: The API isn't showing new uploads

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#434]
### What happened?

Going here https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1

Does not show new models uploaded to the site.  The discord channels shows new models being uploaded however. 

### Steps to reproduce the problem

Go  here https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1

You won't see any new model uploads for the last 5 ish hours.

### What should have happened?

There should be new model uploads when going to the API link.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

**Comment by ghzgod** [comment]
I can see new content, but I cannot see all content. For example, a LORA item on the website does not exist within the API at all.  I've filtered on all the API types (LORA, Checkpoint) etc and it doesn't show up anywhere.  I CAN do a query for that keyword and it will show in the API but not without query

**Comment by RandomInternetPreson** [comment]
Looks like things are working now <3
