### ISSUE TITLE
[Bug]: Creating image post on non model

### ISSUE THREAD

**Issue by PotatoBananaApple** [civitai/civitai#454]
### What happened?

Trying to create image post on non model, for tutorial at this example. Does not post the image to the tutorial as crosspost and only posts it in the model page. This was working before.

### Steps to reproduce the problem

1. Go to [Was trying to post here](https://civitai.com/models/34726/tutorial-for-multidiffusion-upscaler-for-automatic1111-detail-to-the-max)
2. Press "add post"
 
Here it shows the version and everything like it did before too
![image](https://user-images.githubusercontent.com/130109414/231588798-8827d9ae-f775-4036-9078-b9b1399dfd22.png)

3. I drop image to the drag image and then it completely loses information about the tutorial page

![image](https://user-images.githubusercontent.com/130109414/231589170-65d48b39-a87f-4f80-a708-300938429363.png)

### What should have happened?

Before it showed both of them. Here is earlier image i uploaded few days ago and in it it shows both of the resources https://civitai.com/images/454237?modelId=34726&postId=135200&id=34726&slug=tutorial-for-multidiffusion-upscaler-for-automatic1111-detail-to-the-max

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by manuelurenah** [comment]
Hey @PotatoBananaApple I have tested this in production recently and resources seem to be linking properly when making a post to a model. Is this still an issue for you?

**Comment by PotatoBananaApple** [comment]
Hey @manuelurenah , i tested it and it does not post the image to both as crosspost. It does say in the other post that it is a crosspost, but the image does not appear in the original post or link in there in any way.

![1](https://user-images.githubusercontent.com/130109414/233193524-abb1df68-8935-4e0f-bc87-4682b16ebbd5.png)

Added it as "Add post" on: https://civitai.com/models/34726/tutorial-for-multidiffusion-upscaler-for-automatic1111-detail-to-the-max

Can only see it in: https://civitai.com/models/43863/egg-fusion-lora-merge?modelVersionId=48510

Thank you

**Comment by manuelurenah** [comment]
Hey @PotatoBananaApple, we made a release last week which fixed this issue. Feel free to reopen it if it's still a problem for you
