### ISSUE TITLE
[Bug]: Error accessing "your posts" and "your images" from main menu - 404 error displayed

### ISSUE THREAD

**Issue by martin-rizzo** [civitai/civitai#457]
### What happened?

I am experiencing an error on the website where I am unable to access my posts or images from the main menu. When I try to do so, I receive an error message that says "404. The page you are looking for doesn't exist".

### Steps to reproduce the problem

1. Log in to the website.
2. Click on the "Your posts" or "Your images" option in the main menu.
3. Observe that the error message "404. The page you are looking for doesn't exist" is displayed.

### What should have happened?

When I click on the "Your posts" or "Your images" option in the main menu, I should be able to access my posts or images without any errors.

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

I have tried accessing the website on different browsers and devices, I have tried clearing my browser's cache and cookies, but the issue persists.

I would like to note that the "Your models" option in the main menu is functioning correctly, but the issue seems to only affect the "Your posts" and "Your images" options.

**Comment by AreChen** [comment]
I encountered the same problem.

**Comment by manuelurenah** [comment]
Closing this one since it has been fixed

**Comment by MoonRide303** [comment]
It doesn't look like fixed to me:

![image](https://user-images.githubusercontent.com/130458190/233017079-c48f71b2-24ad-4ad5-ae0a-debab0180bc1.png)

**Comment by manuelurenah** [comment]
> It doesn't look like fixed to me:

Hey @MoonRide303, only you're able to see your posts page. Looks like you're not signed in. Please sign in and visit that page again. Let us know if it's still an issue

**Comment by MoonRide303** [comment]
It's 404 when I am signed in, too. I've tried logging out and in, too - it didn't help.

**Comment by manuelurenah** [comment]
> It's 404 when I am signed in, too. I've tried logging out and in, too - it didn't help.

I see the issue now, fix is going out in a couple of minutes
