### ISSUE TITLE
[Bug]: Can't upload second version of model

### ISSUE THREAD

**Issue by crantisz** [civitai/civitai#465]
### What happened?

I tried to upload a new version of model but it shows not found error on step 2.

![image](https://user-images.githubusercontent.com/1749968/231985348-c03f0717-c451-4a12-af58-6ae6de8030b8.png)

### Steps to reproduce the problem

1. Go to a model page
2. Press "+" to add new version 
3. Add information and press Next

### What should have happened?

Should proceed on upload page

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

Here is the link that shows after pressing "next": https://civitai.com/models/28068/model-versions/45432/wizard?step=2

**Comment by manuelurenah** [comment]
That's a weird one, I was able to add a new version to another model. Is this still an issue for you?
