### ISSUE TITLE
[Bug]: "your post" and "your image" is 404

### ISSUE THREAD

**Issue by neavo** [civitai/civitai#466]
### What happened?

I have been unable to open both pages for a few days now

![QQ截图20230414182300](https://user-images.githubusercontent.com/998676/232019746-60014fff-988b-42eb-8cf2-b1b016486413.png)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

normal use

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Microsoft Edge

**Comment by manuelurenah** [comment]
The fix for this is already out
