### ISSUE TITLE
[Bug]: When browsing content related to LoRa, the browser becomes unresponsive.

### ISSUE THREAD

**Issue by ohhhyy** [civitai/civitai#471]
### What happened?

When browsing content related to LoRa, the browser becomes unresponsive. Filtering out LoRa allows for normal browsing, but when viewing pages that contain LoRa, the browser freezes after automatically scrolling down. This issue was tested on a Windows 10 platform using Chrome/Edge browsers.

### Steps to reproduce the problem

1. Go to ....homepage browsing content related to LoRa
2. Press ....Models and by NEWEST
3. ...borowsing about 2 pages

### What should have happened?

well?

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome, Microsoft Edge

**Comment by manuelurenah** [comment]
Hey @ohhhyy, we were experiencing some downtime with our db which may have been the root of the problem. Can you please confirm this is still an issue for you?

**Comment by ohhhyy** [comment]
> Hey @ohhhyy, we were experiencing some downtime with our db which may have been the root of the problem. Can you please confirm this is still an issue for you?

works well now,thx
