### ISSUE TITLE
[Bug]: Image Uploading 'still' broken

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#473]
### What happened?

The image uploading process is still pretty broken

1. You are abusively uploading all images at once, which require a CPU thread per upload, and if chunked, per chunk.
2. Uploading a bunch of 5mb files at once is also not good on any sort of internet with jitter loss. 
3. You have to manually delete all your images with a confirmation, when the image doesn't even exist. Some detection here would be nice so there is no confirmation.
4. Why can't the upload page also just confirm if the file actually exists before publishing and finding out none do? 

### Steps to reproduce the problem

1. Upload images

### What should have happened?

Images should consecutively upload one at a time to ensure it works on even old computers. A lot of people are using colabs on some pretty old tech (I've supported a Celeron D recently in troubleshooting. <.<)

This subsequently will also ensure network traffic isn't blown out for things like mobile internet which is often limited to 10 (T-Mobile home internet for example) connections before it drops the rest, as well as slow internet or internet with jitter loss on high traffic. 

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome, Brave, Microsoft Edge

**Comment by JustMaier** [comment]
Thanks for reporting this. The guy on our team that is most familiar with the internals of our image upload system is out on paternity leave, but as soon as he's back we'll have him jump on this.

**Comment by bkdiehl** [comment]
This should be resolved. We've made some updates to the image uploading UI to better handle image upload errors, and we've added an upload queue system to limit the maximum number of concurrent uploads. The maximum number of concurrent uploads should not be able to exceed the available number of cpu threads.

**Comment by WASasquatch** [comment]
> This should be resolved. We've made some updates to the image uploading UI to better handle image upload errors, and we've added an upload queue system to limit the maximum number of concurrent uploads. The maximum number of concurrent uploads should not be able to exceed the available number of cpu threads.

Awesome! Great work. Hopefully this solves all those pesky issues.
