### ISSUE TITLE
[Bug]:  Downloads randomly resetting

### ISSUE THREAD

**Issue by WASasquatch** [civitai/civitai#474]
### What happened?

So, this model here: https://civitai.com/models/44085 

Had almost 300 downloads, and I was talking to my fiancee about it, and went to show her, and ironically, somehow, the downloads are just reset. What's going on there? 

### Steps to reproduce the problem

N/A

### What should have happened?

Downloads display correctly

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome, Brave, Microsoft Edge

**Comment by manuelurenah** [comment]
We are looking into this at the moment. Rest assure your downloads are still counting, we are just not displaying the total downloads for the model correctly as you can see in the following screenshot 
![image](https://user-images.githubusercontent.com/12631159/233156398-6be8a1b4-5b7a-48b9-887a-11e20888e95c.png)

**Comment by WASasquatch** [comment]
> We are looking into this at the moment. Rest assure your downloads are still counting, we are just not displaying the total downloads for the model correctly as you can see in the following screenshot ![image](https://user-images.githubusercontent.com/12631159/233156398-6be8a1b4-5b7a-48b9-887a-11e20888e95c.png)

Yeah, it looks fixed. It was at like 283 yesterday, and then I went to show my fiancee and it showed like 4 downloads. Lol
