### ISSUE TITLE
[Bug]: No models when browsing on Firefox & logged in

### ISSUE THREAD

**Issue by namelessentity** [civitai/civitai#485]
### What happened?

I log in through my Google account. When I am l logged into my account, all models disappear. I have checked my filter settings and this is not the issue. In my settings I have all content toggled on. This is persistent on all pages, from the front page to my faves to my download history, even to my hidden models. I can't even see the categories.

However, if I log in on Edge everything functions as it should but I'm pretty loathe to use Edge.
![filters](https://user-images.githubusercontent.com/20236678/233522265-2c9fdca5-c36e-43c2-8ad1-76c3f2c271d1.png)
![no-results](https://user-images.githubusercontent.com/20236678/233522267-564c4443-eae6-4602-a3fc-5b14f34f948b.png)

### Steps to reproduce the problem

Unfortunately I'm not sure how to properly reproduce the problem. All I can say is that if I log into my account on Firefox it doesn't work.

### What should have happened?

I should have seen models.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox, Microsoft Edge

**Comment by namelessentity** [comment]
Sorry for the delayed reply, I thought I had notifications turned on for this thread but I didn't. 

I do have some hidden tags and users, yes, but nothing shows up even if I set the view to "show everything", and once again everything works on Edge.

Further info--
* Site loads fine while logged in on Firefox on my netbook and tablet, just not my PC. However I can't really download on either of them, and I only do work on my PC.
* I am using an ad blocker (UBlock Origin) but turning it off doesn't change anything; furthermore it's fine with it on my netbook.

I attached screenshots of Network and Console on both Firefox and Edge, clearly labelled. 
![network-FIREFOX-1](https://user-images.githubusercontent.com/20236678/235354295-1e245645-179e-435b-9bf7-73fcd3e29c02.png)
![network-FIREFOX-2](https://user-images.githubusercontent.com/20236678/235354289-d41c155e-068f-4ce4-9b2a-4f097a1e94b8.png)
![network-EDGE](https://user-images.githubusercontent.com/20236678/235354291-37e43ae5-d9ea-42a4-8136-45c3dd1f343e.png)
![console-FIREFOX](https://user-images.githubusercontent.com/20236678/235354294-fe743488-337b-49c7-8958-7ca4704443ac.png)
![console-EDGE](https://user-images.githubusercontent.com/20236678/235354293-7babe176-8af5-4134-93bd-f00cbffaf4eb.png)

**Comment by namelessentity** [comment]
Oddly, while seeing if I could diagnose anything else myself, I found while logged in, my userpage is a 404, but once again only on Firefox. I saved a model's URL, logged in, and tried to go to it and it was a 404 as well when logged in. Neither page 404'd when logged out.

**Comment by manuelurenah** [comment]
Based on your shared screenshots, seems like firefox is stripping out the referrer header from your request. If the referrer doesn't match in our servers then we block the request hence why you're getting a 401 Unauthorized http error. Please check your browser settings or disable any other extensions that might be removing the referrer from the request

**Comment by namelessentity** [comment]
I disabled all my extensions, and also tried running in safe mode, and it still isn't working, I'm afraid. I haven't done anything in the settings that would have changed this nor do I know what indeed would. If you can provide me any more guidance I am happy to try.

**Comment by namelessentity** [comment]
I currently have zero extensions installed. I temporarily uninstalled them all to aid in debugging.
![Untitled](https://user-images.githubusercontent.com/20236678/235803606-7519b869-247a-4b71-9df1-57dc89a19879.png)

On the 401 errors, there IS no referer listed. The information is the same as in your screenshot, just minus the referer, and that I'm using the Windows version of Firefox.

![Untitled](https://user-images.githubusercontent.com/20236678/235803085-c0e267dd-c763-4025-a8a7-24c27915b60b.png)


This error is in the response windows: json	Object { message: "Please use the public API instead: https://github.com/civitai/civitai/wiki/REST-API-Reference", code: -32001, data: {…} }

I checked the various 401 errors and they all read the same, though some had the error only once.

**Comment by manuelurenah** [comment]
It might be that you changed your browser settings at some point to prevent sending the referrer. Please check this link for more information how to enable it back https://privacyinternational.org/guide-step/4148/change-http-referer-settings-firefox. Also if you need info about what each of the parameters do check this out https://wiki.mozilla.org/Security/Referrer. Hope this helps!

**Comment by namelessentity** [comment]
So I am aware of the config deep settings but I swear I never touched them here and I didn't think to check them until you said-- however, they were all at default values so I don't know still.

So in frustration I just refreshed firefox to default through the troubleshoot menu. I was trying to avoid doing that because I didn't want to set up my browser again but I'd already uninstalled all my extentionsions SOOO. But, that did the trick and it works now so yeah obviously it was something in my settings but hell if I know what.

Thanks so much for troubleshooting this with me, sorry for the bother. Hopefully if anyone else has this issue though this'll help them.
