### ISSUE TITLE
[Bug]: Only up to 10 images show for each modelVersions in /api/v1/models/[id]

### ISSUE THREAD

**Issue by Kalerindel** [civitai/civitai#490]
### What happened?

API endpoints are not displaying all images. Would it be possible to use the same image limit as when uploading the model (20?) in the /api/v1/models endpoint?

This is happening on all (new?) models going and has been like this for a couple of weeks.

As an example:
https://civitai.com/models/46984/badcg-style = 17 images shows in browser
https://civitai.com/api/v1/models/46984  = 10 images in result
https://civitai.com/api/v1/images?modelId=46984 = 0 (!) images in result

### Steps to reproduce the problem

By visiting the links described below and seeing the difference

### What should have happened?

All images related to the model should have been passed back from the endpoints

**Comment by manuelurenah** [comment]
We just released a fix for this issue @Kalerindel

One thing to note is that we are capping images up to 10 items in the array in the `/api/v1/models` endpoint to avoid people abusing it. Instead you can use the `/api/v1/images` endpoint, which should return all images from a specific model. There was a bug before preventing it from getting the images, but should be working now. Please give it a try and let us know if you're still experiencing issues with https://civitai.com/api/v1/images?modelId=46984
