### ISSUE TITLE
[Bug]: nsfw option results in an Internal Server Error

### ISSUE THREAD

**Issue by WIIASD** [civitai/civitai#503]
### What happened?

For some reason nsfw in the url results in an Internal Server Error.
Looked into the commit queue, and seems there's some changes related to nsfw tag.

Ex.
`https://civitai.com/api/v1/images?` works fine but `https://civitai.com/api/v1/images?nsfw=true`

Realized we seems to support nsfw level (None, Soft, Mature, X), but just the api doesn't support it. As soon as the url contains `nsfw` as an variable the request will resulted in an Internal Server Error

### Steps to reproduce the problem

1. Open browser and navigate to `https://civitai.com/api/v1/images?nsfw=true`

### What should have happened?

`https://civitai.com/api/v1/images?nsfw=true` should be returning similar results as `https://civitai.com/api/v1/images?`, but with tag nsfw=true for all images

**Comment by JustMaier** [comment]
Hey thanks for letting us know. We just added "NSFW Levels" and hadn't finished updating the API.
This should be fixed now and we've added documentation about the new NSFW Level options to the API documentation.

If you still have trouble, feel free to re-open the issue :)
