### ISSUE TITLE
[Bug]: Liked models not showing correctly when on the liked models page

### ISSUE THREAD

**Issue by linjunshi** [civitai/civitai#512]
### What happened?

The liked models collection page not showing the models correctly, instead it shows a bunch of other models that are not liked by me. 
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/14053321/235308905-a92a687b-d4e4-4f7f-8b68-6846f9ff5112.png">

### Steps to reproduce the problem

1. Click the profile icon
2. Choose "Liked Models"

### What should have happened?

It should shows the correct liked models instead

**Comment by manuelurenah** [comment]
Actually still happening, taking a deeper look

**Comment by manuelurenah** [comment]
@linjunshi Fix is live, sorry for the inconvenience
