### ISSUE TITLE
[Bug]: Blocking a person doesn't block their comments.

### ISSUE THREAD

**Issue by namelessentity** [civitai/civitai#520]
### What happened?

I'm aware of blocking people via the "hide content from this user" and also by manually putting their name into my filters in my settings. However, it doesn't block any of their comments in discussions. This feels like a bug to me because typically if someone blocks someone, they don't want to see them at all.

### Steps to reproduce the problem

1) Block any user.
2) Check a discussion thread in which they've posted.

### What should have happened?

User should be blocked from my view sitewide, even in discussions and comments.

### What platforms do you use to access the site?

Windows, Android

### What browsers do you use to access the site?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Additional information, context and logs

Chrome on mobile, Firefox on my netbook, Edge on my desktop due to Firefox not working on my desktop for some reason (as in my bug report 485)

**Comment by JustMaier** [comment]
We actually don't support this right now, but it makes sense. We'll get this added

**Comment by JustMaier** [comment]
Ok, this has been added. It'll go out in the next release 👍
