### ISSUE TITLE
[Bug]: API "tags" key inconsistent for models endpoint

### ISSUE THREAD

**Issue by jhlchu** [civitai/civitai#535]
### What happened?

https://civitai.com/api/v1/models?limit=0&username=xyz
outputs tags as array
```
"tags": [
  "character",
  "female",
  "girls",
  "man",
  "landscape",
  "semirealistic"
]
```
https://civitai.com/api/v1/models/000
outputs tags as array of dict
```
 "tags": [
  {
    "name": "character"
  },
  {
    "name": "female"
  },
  {
    "name": "girls"
  },
  {
    "name": "man"
  },
  {
    "name": "landscape"
  },
  {
    "name": "semirealistic"
  }
]
```

### Steps to reproduce the problem

1. Get response from any username at https://civitai.com/api/v1/models?limit=0&username=xyz endpoint.
2. Take the any model from their items list and pass it to https://civitai.com/api/v1/models/000
3. Resulting response shows tags returned in inconsistent with endpoints.

### What should have happened?

Both endpoints should be consistent in how they return the tags list, either as array or array of dicts.

**Comment by JustMaier** [comment]
Just added the fix for this. It should go out in about 12 hours.
