### ISSUE TITLE
[Bug]: Looks like some of the images don't upload correct

### ISSUE THREAD

**Issue by JustMaier** [civitai/civitai#54]
### What happened?

I've occasionally seen some images that failed to upload or something:
![image](https://user-images.githubusercontent.com/607609/205124406-5b017696-2fcd-499a-a418-8a6ee4e28ade.png)

### Steps to reproduce the problem

1. Go to this [page](https://civitai.com/models/1160/dloz-graffiti)

### What should have happened?

I guess some how we need to make sure that the image uploads were successful so that we don't save temp blob urls to the db.

**Comment by JustMaier** [comment]
We've put a check in place to let users know when their image failed to upload but we're still not completely sure why they're failing to upload occasionally.

Hopefully we've stemmed the bleeding.

**Comment by WASasquatch** [comment]
> We've put a check in place to let users know when their image failed to upload but we're still not completely sure why they're failing to upload occasionally.
> 
> Hopefully we've stemmed the bleeding.

It does seem like they are all uploading at once? Which would mean each upload is relying on a CPU thread. If they upload say 12 images, with only a 4 core processor and 8 threads, and then a bunch of PC activity, I'd assume uploads could fail rather often for such users. Same for multi-threaded downloaders and people reporting failed downloads, to find out they're setting 8 threads on a CPU with only 8 threads, and the OS, browser, etc, to allocate to.

**Comment by WASasquatch** [comment]
Still having massive issues all the time guys. 

![Screenshot_3](https://user-images.githubusercontent.com/1151589/223858083-d7578dfd-3051-48ef-b3f0-bb1f8a66e082.png)
![Screenshot_4](https://user-images.githubusercontent.com/1151589/223858106-f966893f-d1ff-4640-896b-1bce7966496a.png)
![Screenshot_5](https://user-images.githubusercontent.com/1151589/223858110-e99c2148-15fa-4c4e-b516-680f385cc2fb.png)
![Screenshot_6](https://user-images.githubusercontent.com/1151589/223858217-b0e0cef5-75d3-4eaa-8259-bdf36511c37b.png)

**Comment by WASasquatch** [comment]
Any word on this? It still happens every upload. Any more then one upload and they pretty much all fail. One at a time works fine. If you made the JS upload all queued sequentially it would probably fix this for everyone. Maybe have a button for multi-threaded. 

Though it seems the uploader script has issues, I don't see this anywhere else, and my CPU (13500kf) and net is more than capable.

**Comment by JustMaier** [comment]
I assume this is failing due to the client-side image nsfw and face detection we run on all of the images. We plan on rolling out a new system that will replace this very soon, which should fix this.

**Comment by sovos15** [comment]
I believe this was fixed in recent weeks.
