### ISSUE TITLE
[Bug]: Using Searchbar from pages other than home page doesn't work

### ISSUE THREAD

**Issue by llsanketll** [civitai/civitai#541]
### What happened?

Searching from a model page doesn't redirect or gives the search result. The search also doesn't work in other pages except the home page.

### Steps to reproduce the problem

1. Go to any model page
2. Press Searchbar
3. Searching the query doesn't redirect the page

### What should have happened?

Should have appended the query to the base of the url but it appends to the end of the current url.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Brave

### Additional information, context and logs

![image](https://github.com/civitai/civitai/assets/55257633/0518f9c3-0780-41b2-ba3a-7da2c69ff207)

**Comment by manuelurenah** [comment]
We noticed this issue yesterday and have already released a fix for it. If this is still happening, please feel free to open it again
