### ISSUE TITLE
[Bug]: Feature flag reduces page size to 20

### ISSUE THREAD

**Issue by matt-b88** [civitai/civitai#552]
### What happened?

https://civitai.com/api/v1/models?favorites=true results in the page size being 20, not the default 100. Requesting a page size of 200 also results in an error 

### Steps to reproduce the problem

1. Have more than 20 models as favourites
2. Navigate to https://civitai.com/api/v1/models?favorites=true
3. Page size is automatically set to 20

### What should have happened?

Page size should not be reduced. 

### What platforms do you use to access the site?

Other/Cloud

### What browsers do you use to access the site?

Google Chrome

**Comment by manuelurenah** [comment]
Hey @matt-b88 I have tested with the steps you mentioned but can't seem to reproduce. I'll close this issue for now cause it seems it has been fixed, but feel free to open it if this is still an issue for you
