### ISSUE TITLE
[Bug]: Invalid environment variables  NEXT_PUBLIC_PICFINDER_WS_ENDPOINT

### ISSUE THREAD

**Issue by elcolie** [civitai/civitai#566]
### What happened?

```bash
event - compiled client and server successfully in 2.1s (7175 modules)
wait  - compiling /api/webhooks/run-jobs (client and server)...
event - compiled successfully in 217 ms (569 modules)
❌ Invalid environment variables:
 NEXT_PUBLIC_PICFINDER_WS_ENDPOINT: Required

wait  - compiling /_error (client and server)...
error - (api)/src/env/client.mjs (19:8) @ eval
error - Error: Invalid environment variables
    at eval (webpack-internal:///(api)/./src/env/client.mjs:19:11)
  17 | if (!_clientEnv.success) {
  18 |   console.error('❌ Invalid environment variables:\n', ...formatErrors(_clientEnv.error.format()));
> 19 |   throw new Error('Invalid environment variables');
     |        ^
  20 | }
  21 |
  22 | for (const key of Object.keys(_clientEnv.data)) {
event - compiled client and server successfully in 301 ms (7330 modules)
❌ Invalid environment variables:
 NEXT_PUBLIC_PICFINDER_WS_ENDPOINT: Required

Error: Invalid environment variables
    at eval (webpack-internal:///./src/env/client.mjs:19:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Invalid environment variables
    at eval (webpack-internal:///./src/env/client.mjs:19:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce the problem

Follow the installation.
```
1. Clone the repository to your local machine.
1. Run `npm install` in the project directory to install the necessary dependencies.
1. Spin up required services with `docker-compose up -d`
    * Note: In addition to postgres and redis, this will also run maildev for email and minio for s3 storage with all necessary buckets automatically created, minio and maildev are not strictly needed but are preferred for testing and development purposes.
1. Create your `.env` by making a copy of the contents from `.env-example` file.
    * Most default values are configured to work with the docker-compose setup, with the exception of the S3 upload key and secret. To generate those, navigate to the minio web interface at [http://localhost:9000](http://localhost:9000) with the default username and password `minioadmin`, and then navigate to the "Access Keys" tab. Click "Create Access Key" and copy the generated key and secret into the `.env` file.
    * Set `WEBHOOK_TOKEN` to a random string of your choice. This will be used to authenticate requests to the webhook endpoint.
1. Run `npm run db:migrate` to run all database migrations.
1. Run `npm run db:generate` to generate the prisma client.
1. Start the development server by running `npm run dev`.
1. Visit the page `http://localhost:3000/api/webhooks/run-jobs?token=WEBHOOK_TOKEN&run=update-metrics` to start the metrics update job (make sure to substitute `WEBHOOK_TOKEN`)
1. Finally, visit [http://localhost:3000](http://localhost:3000) to see the website.
    * Note that account creation will run emails through maildev, which can be accessed at [http://localhost:1080](http://localhost:1080).
    * Also note that Cloudflare credentials are necessary in order for image uploads to work.
```

### What should have happened?

No error and be able to use website

### What platforms do you use to access the site?

MacOS

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

❯ nvm --version
0.39.0
> node v20.3.0

**Comment by 1chenyx** [comment]
I also have this problem

**Comment by hardwarelayer** [comment]
I have same issue

**Comment by 1chenyx** [comment]
The reason is that someone did not submit the configuration file for the corresponding environment variable when submitting it. env
![image](https://github.com/civitai/civitai/assets/127660408/eb0a3861-87f0-4341-9f27-85890c2f23ac)

**Comment by 1chenyx** [comment]
> 

Using previous versions

**Comment by hardwarelayer** [comment]
I tried release branch, same issue

**Comment by brianschamel** [comment]
I'm somewhat new to using github - I'm used to SVN.  What is the basic series of commands I'd need to run to get an older version?  I tried using these commands to reset to an older version just before :

  26 git reset --hard c116d1d
  27 git pull

And git pull is showing a lot of changes after this, but the schema.mjs file isn't changing (and I still get the same error when trying to access the URL to update the metrics)

**Comment by brianschamel** [comment]
I'm somewhat new to github - what is the commit i'd need to revert to in order to get this working? I tried the parent of the commit here (c116d1d), but that's giving me a different error:

 CLICKHOUSE_TRACKER_URL: Invalid url

**Comment by PeterNjeim** [comment]
This is the commit I've been using:

commit f66dfdef409696b387b27bb199ca2dcf998888fe
Author: Justin Maier <Zipp425@gmail.com>
Date:   Wed May 17 16:32:58 2023 -0600

    Delete images when deleting a post

**Comment by PeterNjeim** [comment]
This is the commit I've been using: f66dfdef409696b387b27bb199ca2dcf998888fe

**Comment by ViktorPlohl** [comment]
Could someone provide the appropriate environment variable values for `PICFINDER_WS_ENDPOINT` and `PICFINDER_API_KEY`?
@manuelurenah

**Comment by manuelurenah** [comment]
Hey guys, unfortunately we cannot provided the values for those env vars. So, to enable y'all to spin up the server without those errors, we made them optional. Should be good now if you pull the latest commit

**Comment by NicksonYap** [comment]
@manuelurenah  this line is enforcing `ORCHESTRATOR_ENDPOINT` and `ORCHESTRATOR_ACCESS_TOKEN` to be required, although in `schema.mjs` it has been made optional

https://github.com/civitai/civitai/blob/bebed7ada44a1167d298403bbc01cbfa21941b4c/src/server/http/orchestrator/orchestrator.caller.ts#L13

```js
  static getInstance(): OrchestratorCaller {
    if (!env.ORCHESTRATOR_ENDPOINT) throw new Error('Missing ORCHESTRATOR_ENDPOINT env');
    if (!env.ORCHESTRATOR_ACCESS_TOKEN) throw new Error('Missing ORCHESTRATOR_ACCESS_TOKEN env');
//...
```

**Comment by johndpope** [comment]
@manuelurenah  - fyi  - it's still not good.
