### ISSUE TITLE
[Bug]: Server restart today caused API call issue

### ISSUE THREAD

**Issue by RandomInternetPreson** [civitai/civitai#583]
### What happened?

I'm not 100% sure what happened, I've been using curl to talk to the API 

'curl -X GET -H --tlsv1.3  "https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1"'

and everything has been working for months, but after the server hiccup today I don't get the API data anymore I get this instead:

    '  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                      Dload  Upload   Total   Spent    Left  Speed
     
       0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     '

### Steps to reproduce the problem

Using this: https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1
works fine in a browser, but calling it using curl does not provide the API data

### What should have happened?

I should be getting the API data when I use 'curl -X GET -H --tlsv1.3  "https://civitai.com/api/v1/models?limit=100&sort=Newest&page=1"'

**Comment by JustMaier** [comment]
Hey @RandomInternetPreson are you still having this issue? It looks like there may have been some bad data in the cloudflare cache that could have led to your issue. We've reset the cache now

**Comment by RandomInternetPreson** [comment]
Woot!! Yes! Everything is working properly now! Thank you <3
