### ISSUE TITLE
API documentation is missing cursor based pagination details

### ISSUE THREAD

**Issue by worthlesscog** [civitai/civitai#588]
The API switched from "page=n" to cursor based pagination but there are no examples of how to use this style of navigation in the documentation.

**Comment by JustMaier** [comment]
Sorry for the change without warning. The prior paging system was causing significant system issues as the DB had to see to really high offsets now that there are so many images.
We'll get the new cursor system documented by tomorrow. To try and at least provide a simple migration for people using the paging system, we've left the `nextPage` url in the metadata to make it easy to get the next set of results whether you started with paging or a cursor.

**Comment by JustMaier** [comment]
Ok, the documentation of the endpoint has been updated. Let me know if you have any trouble or need help and we can re-open this :)

**Comment by z3ugma** [comment]
@JustMaier where did the documentation change? The docs at https://github.com/civitai/civitai/wiki/REST-API-Reference#get-apiv1images still suggest using Page?

**Comment by simonmcnair** [comment]
I agree, the documentation doesn't seem to reflect anyhing except that you need to use a cursor.
