### ISSUE TITLE
[Bug]: The metadata of the image API is missing the 'totalItems' and 'totalPages' fields.

### ISSUE THREAD

**Issue by sunnyark** [civitai/civitai#591]
### What happened?

The metadata of the image API is missing the 'totalItems' and 'totalPages' fields. I would like to know if this is a temporary error or if they have been permanently removed from the provided data. I need accurate metadata for the image API. Thank you.

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

I need accurate metadata for the image API

**Comment by JustMaier** [comment]
Hey @sunnyark I'm assuming you saw the note about the change to the Image API in the docs. Sorry for the sudden change, the total items and paging system we previously supported isn't scaling well now that there are so many images. Let me know if you have trouble with the cursor system.

**Comment by sunnyark** [comment]
@JustMaier Understood. So, recently I also switched to cursor-based approach. However, I have some doubts about the results returned by the cursor. I have raised a new issue regarding this. Please take a look and confirm
