### ISSUE TITLE
[Bug]: NSFW selector 'X' doesn't work properly for images

### ISSUE THREAD

**Issue by worthlesscog** [civitai/civitai#592]
### What happened?

I'm assuming 'X' is higher than 'Mature' in which case, it doesn't appear to work properly. If not, disregard this ticket but document how it's supposed to work. The API documentation looks like there are supposed to be 4 increasing levels of maturity.

This model https://civitai.com/api/v1/images?modelId=98925 contains 9 images rated 'None', 0 rated 'Soft', 6 rated 'Mature' and 0 rated 'X'.

Specifying None, Soft and Mature work as expected returning only those images. Specifying 'X' returns 'Mature'

Thundercats! Ho!

### Steps to reproduce the problem

1. Go to .... https://civitai.com/api/v1/images?modelId=98925&nsfw=X

### What should have happened?

You should get back an empty list of images as there aren't any graded 'X' for that model.

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

This ticket assumes the maturity levels are graded in increasing maturity order from None to X. If that's not the case, the API documentation is insufficient to explain how the nsfw selector is supposed to work.

**Comment by manuelurenah** [comment]
Hey @worthlesscog the way that filter works is that it will fetch images up to the nsfw level that you specify. For example, if you specify `Mature`, it will retrieve images marked as `Soft` and `Mature`, if you send `Soft` it'll bring just images marked as `Soft` and finally `X` will retrieve images with `Soft`, `Mature` and `X`

Hope this helps!

**Comment by worthlesscog** [comment]
Then it's broken in a different way - specifying "Mature" only returns Mature not Mature and lower, which isn't how you've indicated it's supposed to work. With the model I linked None returns the 9 marked as None, Soft returns an empty list and Mature returns only the 6 marked Mature.

The only way to get the images marked None is to not specify at all or specify None.
