### ISSUE TITLE
[Bug]: LyCORIS extension deprecated, should not be suggested to the user

### ISSUE THREAD

**Issue by catboxanon** [civitai/civitai#693]
### What happened?

Visiting any page for a LyCORIS (LoCon / LoHA) model shows the following info:
![image](https://github.com/civitai/civitai/assets/122327233/dad504b3-9e0c-45e0-b585-796ce9278ed4)

This should no longer be shown, and shouldn't have been for months, as for version 1.5.0 of the webui, [support was implemented natively](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11821), and furthermore [the extension is now deprecated](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris#notice). 

### Steps to reproduce the problem

n/a

### What should have happened?

The extension should not be recommended to the user.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

The webui has gotten several issue reports due to this. See https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13085 as a recent example.

**Comment by JustMaier** [comment]
Thanks for the heads up. We've removed this notice.
