### ISSUE TITLE
[Bug]: LoRA hashes are not using correct hash function

### ISSUE THREAD

**Issue by catboxanon** [civitai/civitai#742]
### What happened?

LoRAs whose file format is `.safetensors` are currently read in their entirety to calculate the hash. This is not how it should be done. Because there is very often metadata embedded in this format, and is done so by default, kohya-ss had implemented a function to hash only the weights (the part of the file that would remain unchanged). This is also how the webui calculates the hash.

https://github.com/kohya-ss/sd-scripts/blob/4c6f3125fce31f86aa949026030e923f3d7d826b/library/train_util.py#L1679-L1693
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/102b6617dacffdcc89c56badcaae6c5e83c3ff21/modules/hashes.py#L66-L80
https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/b59deaa382bf5c968419eff4559f7d06fc0e76e7/modules/hashes.py#L69-L83

### Steps to reproduce the problem

1. View any LoRA page. Using https://civitai.com/models/101104 as an example.
2. Several truncated hashes are listed.
3. None of these match what the webui calculates (`a33ded9e396c`)

### What should have happened?

There should have been a hash listed that only hashed the model weights.

**Comment by paboum** [comment]
I used https://github.com/arenasys/stable-diffusion-webui-model-toolkit to prune 1000+ Loras stored locally. Now I can't use https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper to index and update those Loras. Either Civitai should prune all Loras before calculating the hash, or do what @catboxanon suggested.
