### ISSUE TITLE
[Bug]: Inpainting models aren't working because filename is renamed without -inpainting suffix

### ISSUE THREAD

**Issue by Lushness** [civitai/civitai#84]
### What happened?

Inpainting models aren't working right because the filename is changed when downloaded (or uploaded), which removes the `-inpainting` suffix at the end of the filename. The filename has to end with `-inpainting.ckpt` in order to work as an inpainting model in Auto1111. There is a PR for Auto1111 that changes this behavior that will recognize inpainting models without the suffix, but I don't think it has been implemented yet. Does Civitai rename the files when they are uploaded or downloaded?

### Steps to reproduce the problem

1. Download an inpainting model
2. The model won't load in Auto1111 and throws errors
3. The model filename has to be renamed with `-inpainting` at the end, before the .ckpt extension, to get it to work

### What should have happened?

The filename has to keep the `-inpainting` suffix at the end in order for Auto1111 to recognize the model as an inpainting model.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Microsoft Edge

**Comment by JustMaier** [comment]
Thanks for the heads up on this. I'll address this now.

**Comment by JustMaier** [comment]
@Lushness I think I fixed this. Do you know a model that was causing issues so I can confirm?

**Comment by Lushness** [comment]
@JustMaier it was [this NSFW inpainting model](https://civitai.com/models/1245/airoticarts-penis-model). I think you fixed it, as it shows -inpainting at the end of the filename now when downloaded. Thanks!
