### ISSUE TITLE
[Bug]: HEAD requests to download URLs endlessly hang

### ISSUE THREAD

**Issue by isaac-mcfadyen** [civitai/civitai#881]
### What happened?

When sending a HEAD request to the API, the request endlessly hangs and never completes.

There's a couple of download clients that use the HEAD method to check the file size before downloading, and those fail since the HEAD request just hangs forever.

### Steps to reproduce the problem

1. Find any model and pick any version from the API.
2. Send a HEAD request to its download URL via `curl --head <URL>`
    - For example, `curl --head https://civitai.com/api/download/models/126688 -v`
3. Observe as the request hangs and never completes.

### What should have happened?

Usually the HEAD method is used to return only headers about the object being fetched such as Content-Length and Content-Type.

In the case of R2, there's a `head()` method that can be used to fetch the headers quickly from R2 if this is running inside a Worker. See https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#bucket-method-definitions.

### What platforms do you use to access the site?

Other/Cloud

### What browsers do you use to access the site?

Google Chrome

**Comment by manuelurenah** [comment]
This endpoint only allows GET requests

**Comment by isaac-mcfadyen** [comment]
> This endpoint only allows GET requests

I understand that, yeah. I'm just wondering whether HEAD requests should be allowed, given a lot of download clients use them for Range requests so that they don't need to redownload the whole file when resuming? Is there a specific reason for not supporting HEAD requests? 🙂

**Comment by sansmoraxz** [comment]
@isaac-mcfadyen did you figure out a foolproof way to make ranged download?

I can't normally trust file sizes in floating point for making accurate measures of content length.
