### ISSUE TITLE
"returnfalse is not defined" Error and Network Errors in _app-0f312fc4541f7480.js

### ISSUE THREAD

**Issue by KillshotELOx** [civitai/civitai#903]
### What happened?

What Happened?

JavaScript error "returnfalse is not defined" occurred in _app-0f312fc4541f7480.js.
Multiple network errors (401, 404, blocked resources) encountered.

![Screenshot 2023-12-22 140958](https://github.com/civitai/civitai/assets/153048533/fc1a378f-fb5e-4fbd-8d85-50f6cfd1bc32)

### Steps to reproduce the problem

Key Errors:

"returnfalse is not defined": This indicates a missing or undefined function or variable named "returnfalse" within the JavaScript code at the specified file and line numbers.
Multiple network errors (401, 404, blocked resources): These suggest issues with resource accessibility, potentially due to authentication failures, incorrect URLs, or content blocking.
Potential Causes:

Missing or Incorrect Code: The "returnfalse" function or variable might be absent, misspelled, or have incorrect scope.
JavaScript Errors: Other syntax errors or logical flaws in the code could be contributing.
Network Connectivity Issues: Server unavailability, network restrictions, or misconfigured URLs could be preventing resource loading.
Authentication Problems: Incorrect credentials or authorization failures might be causing 401 errors.
Content Blocking: Firewalls or browser extensions might be blocking certain resources.
Next Steps:

Examine the Code:

Carefully review the code around lines 2919144 and 2922540 in _app-0f312fc4541f7480.js for errors or missing definitions.
Check for typos, incorrect variable names, or scoping issues.
Ensure that "returnfalse" is defined and accessible within the relevant scope.

![Screenshot 2023-12-22 140958](https://github.com/civitai/civitai/assets/153048533/39b9bbf0-740e-4cf2-9f49-0bb12d96b986)

### What should have happened?

What Should Have Happened:

The JavaScript code should have executed without errors.
Resources should have loaded successfully without network issues.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Google Chrome

### Additional information, context and logs

![Screenshot 2023-12-22 140958](https://github.com/civitai/civitai/assets/153048533/075052c1-8065-4b3a-a595-b101de056bbe)
![Screenshot 2023-12-22 141715](https://github.com/civitai/civitai/assets/153048533/432b4b85-9e5d-47b5-9251-507c4436a5b2)

**Comment by manuelurenah** [comment]
Our image generation services where showing degradation the last couple of days. However, they're in a more stable state right now and you should be able to generate images using the in-app generator. Feel free to open the issue again if this is still present for you
