### ISSUE TITLE
[Bug]: Unable to log in with email

### ISSUE THREAD

**Issue by siupenyau** [civitai/civitai#907]
### What happened?

Hi,

After I clicked the link in email, an error message "Login error" and "Unable to sign in" was given. What is the possible reason(s)?

### Steps to reproduce the problem

1. Go to ....Log in with email
2. Press ....the provided link in email
3. ...Unable to sign in.

### What should have happened?

Successful login the past.

### What platforms do you use to access the site?

Windows

### What browsers do you use to access the site?

Mozilla Firefox

**Comment by manuelurenah** [comment]
I tried reproducing this issue, but login with email seems to be working fine at the moment. If this is still a problem for you, try right clicking the Sign In button in the email and copy/paste the provided url in your browser. That should help

**Comment by d6e132ce90a0** [comment]
@manuelurenah For me, this issue remains.
I am using Firefox 121.0 on Linux. I'm making it to the point where I am to accept the TOS. When clicking the accept button, it is sending a POST to https://civitai.com/api/trpc/user.acceptTOS with the body
```json
{"json":null,"meta":{"values":["undefined"]}}
```
and the server responds with 401 Unauthorized and the body
```json
{"error":{"json":{"message":"Please use the public API instead: https://github.com/civitai/civitai/wiki/REST-API-Reference","code":-32001,"data":{"code":"UNAUTHORIZED","httpStatus":401,"path":"user.acceptTOS"}}}}
```

**Comment by siupenyau** [comment]
At this moment, copying the link instead of clicking the button somehow works in my case. I am also using Firefox.

Hope this helps.

**Comment by d6e132ce90a0** [comment]
Does not work for me. Should this be a new issue then, since it works for OP?

**Comment by d6e132ce90a0** [comment]
https://github.com/civitai/civitai/issues/936
