### ISSUE TITLE
[Bug]: Trying to download Training Data fails with `File not found`

### ISSUE THREAD

**Issue by xzuyn** [civitai/civitai#935]
### What happened?

Clicking the download link for any training data fails.

Examples:
1. https://civitai.com/api/download/training-data/264334 or https://civitai.com/api/download/models/264334?type=Training%20Data
2. https://civitai.com/api/download/training-data/71755 or https://civitai.com/api/download/models/71755?type=Training%20Data
3. https://civitai.com/api/download/training-data/264335 or https://civitai.com/api/download/models/264335?type=Training%20Data
4. https://civitai.com/api/download/training-data/79203 or https://civitai.com/api/download/models/79203?type=Training%20Data
5. https://civitai.com/api/download/training-data/121999 or https://civitai.com/api/download/models/121999?type=Training%20Data
6. https://civitai.com/api/download/training-data/122454 or https://civitai.com/api/download/models/122454?type=Training%20Data
7. https://civitai.com/api/download/training-data/157917 or https://civitai.com/api/download/models/157917?type=Training%20Data
8. https://civitai.com/api/download/training-data/162685 or https://civitai.com/api/download/models/162685?type=Training%20Data

### Steps to reproduce the problem

1. Go to any page which contains training data.
2. Press the download link for the training data.
3. It won't work.

### What should have happened?

It should download.

### What platforms do you use to access the site?

Windows, Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

I also tested in Vivaldi browser and using `wget` on the links. Those don't work either.

**Comment by xzuyn** [comment]
> @xzuyn Thank you for bringing this up to our attention. The problem has been fixed!

Thanks for the quick fix. Any chance this idea could be looked at some time? https://github.com/orgs/civitai/discussions/807

**Comment by remixer-dec** [comment]
I am experiencing the same issue on some models: 
https://civitai.com/api/download/models/316022?type=Training%20Data
https://civitai.com/api/download/models/315960?type=Training%20Data
