### ISSUE TITLE
[Bug]: Cannot accept ToS on account creation

### ISSUE THREAD

**Issue by d6e132ce90a0** [civitai/civitai#936]
### What happened?

When creating an account I cannot accept the terms of service and am therefore stuck in the onboarding process.

### Steps to reproduce the problem

1. Register a new account (I tried both using GitHub and email)
2. Click the email verification link in case of email / Be redirected to the onboarding process in case of Github
3. Click the "Accept" button on the page showing you the Terms of Service
4. Problem: A loading symbol appears and disappears right away as part of the button, nothing else happens

### What should have happened?

I should have been redirected to the next step "Account - Verify your details"

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

When clicking the accept button, it is sending a POST to https://civitai.com/api/trpc/user.acceptTOS with the body
```json
{"json":null,"meta":{"values":["undefined"]}}
```
and the server responds with 401 Unauthorized and the body
```json
{"error":{"json":{"message":"Please use the public API instead: https://github.com/civitai/civitai/wiki/REST-API-Reference","code":-32001,"data":{"code":"UNAUTHORIZED","httpStatus":401,"path":"user.acceptTOS"}}}}
```

**Comment by manuelurenah** [comment]
This seems like a cache issue, please try using an incognito tab to login with email and see if that helps. I did reset your account session (no data has been lost or erased from your account), but everything seems fine with it.

**Comment by d6e132ce90a0** [comment]
I just tried it, with the same result

**Comment by d6e132ce90a0** [comment]
I tried it with a different instance of Firefox in a VM, it works. Must have something to do with Firefox's privacy settings
