### ISSUE TITLE
[Bug]: api endpoint changed. 

### ISSUE THREAD

**Issue by eddyizm** [civitai/civitai#975]
### What happened?

previously this was working up until 2 days ago. 
`wget -O 'models/loras/ab0m.safetensors' https://civitai.com/api/download/models/138296?type=Model&format=SafeTensor`

Now it fails, creates a small file that is corrupted. 

### Steps to reproduce the problem

Looking at the api docs, looks like there was a switch to a token, so I created an api token from the website

`curl -IL -H "Content-Type: application/json" -H "Authorization: Bearer my_api_token" -X GET https://civitai.com/api/download/models/55777?type=Model&format=SafeTensor`

Job just hangs and results in the following output

```  
$ HTTP/1.1 307 Temporary Redirect
Date: Fri, 26 Jan 2024 00:13:29 GMT
Transfer-Encoding: chunked
Connection: keep-alive
location: https://civitai-delivery-worker-prod.5ac0637cfd0766c97916cefa3764fbdf.r2.cloudflarestorage.com/1362997/model/bodhorV1.eq23.safetensors?X-Amz-Expires=86400&response-content-disposition=attachment%3B%20filename%3D%22BodHor-V1.safetensors%22&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=e01358d793ad6966166af8b3064953ad/20240126/us-east-1/s3/aws4_request&X-Amz-Date=20240126T001329Z&X-Amz-SignedHeaders=host&X-Amz-Signature=7d4a4131bb2bb5cb985a3c1f9e4675e0e336fe638ef81f396271552a32deb568
strict-transport-security: max-age=15724800; includeSubDomains
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 84b48ce1b8b731cd-LAX
alt-svc: h3=":443"; ma=86400

HTTP/1.1 200 OK
Date: Fri, 26 Jan 2024 00:13:29 GMT
Content-Type: application/octet-stream
Content-Length: 37863410
Connection: keep-alive
Accept-Ranges: bytes
Content-Disposition: attachment; filename="BodHor-V1.safetensors"
ETag: "25c0f6a6d9248b2f63f463d5dc3619b4"
Last-Modified: Tue, 14 Nov 2023 00:37:17 GMT
Server: cloudflare
CF-RAY: 84b48ce3da262ee4-LAX
```

### What should have happened?

it should download the lora or model to the local file system.
shows http 200 but nothing happens. 

### What platforms do you use to access the site?

Linux

### What browsers do you use to access the site?

Mozilla Firefox

### Additional information, context and logs

this is also not working on google colab which is just a jupyter notebook but their infrastructure is really fast.,

**Comment by JustMaier** [comment]
It appears that the creator of the resource you're attempting to download has required authentication. We actually return a 401 in these scenarios unless you include an API Token.

If you try this instead:
```
https://civitai.com/api/download/models/138296?type=Model&format=SafeTensor&token={yourAPIToken}
```
It should download just fine :)

**Comment by eddyizm** [comment]
looks like the missing piece on my end was the url needed to be quoted. 

Thanks for your help!
